@AbapCatalog.sqlViewName: 'zcds_row_count'
@ClientDependent: true
@AbapCatalog.compiler.CompareFilter: true
@EndUserText.label: 'Test CDS Row count'
define view ZCDS_test_rowcount
    with parameters p_journal : ISMMATNR_PRODUCT,
/*          p_media_issue : ISMMATNR_ISSUE,
          p_publication_date : ISMPUBLDATE,
          p_init_ship_date : ISMERSTVERDAT,
          p_delivery_date : JSHIPPING_DATE,
          p_actual_gi_date : ISMANLFTAGI,
          p_sales_org : VKORG,
          p_dist_channel : VTWEG,
          p_division : SPART,
          p_sales_office : VKBUR,
*/          p_contract : VBELN_VA
/*          p_assignment : abap.char(30),
          p_doc_type : AUART,
          p_item_category : PSTYV,
          p_contract_start_date : VBDAT_VEDA,
          p_contract_end_date : VNDAT_VEDA,
          p_release_order : VBELN,
          p_bill_block_flag : abap.char(3),
          p_del_block_flag : abap.char(3),
          p_credit_block_flag : abap.char(3),
          p_cancel_ord_flag : abap.char(3),
          p_cancel_res_flag : abap.char(3),
          p_rel_ord_flag : abap.char(3),
          p_unearned_flag : abap.char(3)
*/          
as select from Zcds_Media_Issue_R115_Rept {

key mandt,
key Contract,
key Item,
key Assignment,
key Contract_start_date,
key Contract_end_date,
key Acceptance_date,
key Req_cancellation_date,
key Media_issue,
key Journal,
key Publication_date,
key Actual_gi_date,
key Profit_center,
key Material_status,
key Distr_chain_status,
key Issue_number,
key Vol_copy_no,
key Year_number,
key Publication_type,
key Release_order_created,
key Status,
key Plan_status_desc,
key Planned_RO_from,
key Planned_RO_to,
key Release_order,
key Release_order_item,
key PO_number,
key PO_item,
key PO_type,
key PO_del_ind,
key PO_info_rec,
key PO_qty,
key Delivery_number,
key Delivery_item,
key Purchase_requisition,
key Purchase_requisition_item,
key Mat_doc,
key Mat_doc_item,
key Mat_doc_type,
key Mat_doc_year,
key Mat_doc_date,
key Item_category,
key Relevant_RAR,
key Cancel_reason,
key Cancel_reason_desc,
key Reason_for_cancel,
key reason_for_cancel_desc,
key cancelled_orders,
key cancelled_orders_desc,
key Billing_block,
key Billing_block_desc,
key Delivery_block,
key Delivery_block_desc,
key Overall_doc_status,
key Overall_status_desc,
key Credit_status,
key Credit_status_desc,
key Sales_org,
key Dist_channel,
key Division,
key Doc_type,
key Sales_office,
key issue_count,
key net_value,
key value_per_issue,
key Earned_amount,
key Billed_amount,
key Balance,
key Document_currency,
key Contract_reason,
key Contract_qty,
key Plant,
key Mat_grp_5,
key Mat_grp_3,
key Net_value_item,
key Currency,
key Price_grp,
key Price_grp_desc,
key MI_IC_group,
key Dist_chain_status,
key Del_plant,
key Bill_block_flag,
key Del_block_flag,
key credit_block_flag,
key cancel_ord_flag,
key cancel_res_flag,
key rel_ord_flag,
key unearned_flag,
key Vendor,
key Vendor_name,
key delivery_date,
key init_ship_date,

count(*) as sales_orders_count    
}
group by

Contract,
Item,
Assignment,
Contract_start_date,
Contract_end_date,
Acceptance_date,
Req_cancellation_date,
Media_issue,
Journal,
Publication_date,
Actual_gi_date,
Profit_center,
Material_status,
Distr_chain_status,
Issue_number,
Vol_copy_no,
Year_number,
Publication_type,
Release_order_created,
Status,
Plan_status_desc,
Planned_RO_from,
Planned_RO_to,
Release_order,
Release_order_item,
PO_number,
PO_item,
PO_type,
PO_del_ind,
PO_info_rec,
PO_qty,
Delivery_number,
Delivery_item,
Purchase_requisition,
Purchase_requisition_item,
Mat_doc,
Mat_doc_item,
Mat_doc_type,
Mat_doc_year,
Mat_doc_date,
Item_category,
Relevant_RAR,
Cancel_reason,
Cancel_reason_desc,
Reason_for_cancel,
reason_for_cancel_desc,
cancelled_orders,
cancelled_orders_desc,
Billing_block,
Billing_block_desc,
Delivery_block,
Delivery_block_desc,
Overall_doc_status,
Overall_status_desc,
Credit_status,
Credit_status_desc,
Sales_org,
Dist_channel,
Division,
Doc_type,
Sales_office,
issue_count,
net_value,
value_per_issue,
Earned_amount,
Billed_amount,
Balance,
Document_currency,
Contract_reason,
Contract_qty,
Plant,
Mat_grp_5,
Mat_grp_3,
Net_value_item,
Currency,
Price_grp,
Price_grp_desc,
MI_IC_group,
Dist_chain_status,
Del_plant,
Bill_block_flag,
Del_block_flag,
credit_block_flag,
cancel_ord_flag,
cancel_res_flag,
rel_ord_flag,
unearned_flag,
Vendor,
Vendor_name,
delivery_date,
init_ship_date
