*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_EXCL_RESN.................................*
FORM GET_DATA_ZQTCV_EXCL_RESN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_EXCL_RESN WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_EXCL_RESN .
ZQTCV_EXCL_RESN-MANDT =
ZQTC_EXCL_RESN-MANDT .
ZQTCV_EXCL_RESN-EXCL_RESN =
ZQTC_EXCL_RESN-EXCL_RESN .
    SELECT SINGLE * FROM ZQTCT_EXCL_RESN WHERE
EXCL_RESN = ZQTC_EXCL_RESN-EXCL_RESN AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZQTCV_EXCL_RESN-EXCL_RESN_D =
ZQTCT_EXCL_RESN-EXCL_RESN_D .
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_EXCL_RESN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_EXCL_RESN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_EXCL_RESN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_EXCL_RESN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_EXCL_RESN WHERE
  EXCL_RESN = ZQTCV_EXCL_RESN-EXCL_RESN .
    IF SY-SUBRC = 0.
    DELETE ZQTC_EXCL_RESN .
    ENDIF.
    DELETE FROM ZQTCT_EXCL_RESN WHERE
    EXCL_RESN = ZQTC_EXCL_RESN-EXCL_RESN .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_EXCL_RESN WHERE
  EXCL_RESN = ZQTCV_EXCL_RESN-EXCL_RESN .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_EXCL_RESN.
    ENDIF.
ZQTC_EXCL_RESN-MANDT =
ZQTCV_EXCL_RESN-MANDT .
ZQTC_EXCL_RESN-EXCL_RESN =
ZQTCV_EXCL_RESN-EXCL_RESN .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_EXCL_RESN ##WARN_OK.
    ELSE.
    INSERT ZQTC_EXCL_RESN .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZQTCT_EXCL_RESN WHERE
    EXCL_RESN = ZQTC_EXCL_RESN-EXCL_RESN AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZQTCT_EXCL_RESN.
ZQTCT_EXCL_RESN-EXCL_RESN =
ZQTC_EXCL_RESN-EXCL_RESN .
ZQTCT_EXCL_RESN-SPRAS =
SY-LANGU .
      ENDIF.
ZQTCT_EXCL_RESN-EXCL_RESN_D =
ZQTCV_EXCL_RESN-EXCL_RESN_D .
    IF SY-SUBRC = 0.
    UPDATE ZQTCT_EXCL_RESN ##WARN_OK.
    ELSE.
    INSERT ZQTCT_EXCL_RESN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_EXCL_RESN-UPD_FLAG,
STATUS_ZQTCV_EXCL_RESN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_EXCL_RESN.
  SELECT SINGLE * FROM ZQTC_EXCL_RESN WHERE
EXCL_RESN = ZQTCV_EXCL_RESN-EXCL_RESN .
ZQTCV_EXCL_RESN-MANDT =
ZQTC_EXCL_RESN-MANDT .
ZQTCV_EXCL_RESN-EXCL_RESN =
ZQTC_EXCL_RESN-EXCL_RESN .
    SELECT SINGLE * FROM ZQTCT_EXCL_RESN WHERE
EXCL_RESN = ZQTC_EXCL_RESN-EXCL_RESN AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZQTCV_EXCL_RESN-EXCL_RESN_D =
ZQTCT_EXCL_RESN-EXCL_RESN_D .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_EXCL_RESN-EXCL_RESN_D .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_EXCL_RESN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_EXCL_RESN-EXCL_RESN TO
ZQTC_EXCL_RESN-EXCL_RESN .
MOVE ZQTCV_EXCL_RESN-MANDT TO
ZQTC_EXCL_RESN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_EXCL_RESN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_EXCL_RESN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_EXCL_RESN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZQTC_EXCL_RESN-EXCL_RESN TO
ZQTCT_EXCL_RESN-EXCL_RESN .
MOVE SY-LANGU TO
ZQTCT_EXCL_RESN-SPRAS .
MOVE ZQTCV_EXCL_RESN-MANDT TO
ZQTCT_EXCL_RESN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTCT_EXCL_RESN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTCT_EXCL_RESN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTCT_EXCL_RESN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
