* INCLUDE MJPG0TC0.
*----------------------------------------------------------------------*
* Konstanten der Ausgabenfolge                                        *
*----------------------------------------------------------------------*
DATA: SEL_VARIANTE LIKE RJP_MG0-SEL_VARIANTE.
* Konstanten
CONSTANTS: CON_SEL_INITIAL LIKE SEL_VARIANTE VALUE '0'.
CONSTANTS: CON_SEL_ZEITRAUM LIKE SEL_VARIANTE VALUE '1'.
CONSTANTS: CON_SEL_ZEITRAUM_OHNE_VONDAT LIKE SEL_VARIANTE VALUE '2'.
CONSTANTS: CON_SEL_ZEITRAUM_OHNE_BISDAT LIKE SEL_VARIANTE VALUE '3'.
CONSTANTS: CON_SEL_HEFTNR   LIKE SEL_VARIANTE VALUE '4'.
CONSTANTS: CON_SEL_HEFTNR_OHNE_VONHEFT LIKE SEL_VARIANTE VALUE '5'.
CONSTANTS: CON_SEL_HEFTNR_OHNE_BISHEFT LIKE SEL_VARIANTE VALUE '6'.
CONSTANTS: CON_SEL_MATNR    LIKE SEL_VARIANTE VALUE '7'.
CONSTANTS: CON_SEL_MATNR_OHNE_VONMATNR LIKE SEL_VARIANTE VALUE '8'.
CONSTANTS: CON_SEL_MATNR_OHNE_BISMATNR LIKE SEL_VARIANTE VALUE '9'.
