"Name: \PR:SDPIQPRICELIST\EX:ES_PIQ_SDPRICELIST_EXT5\EI
ENHANCEMENT 0 ZQTC_SDPRICELST_EXT5.
TABLES:a985,a950.



SELECTION-SCREEN BEGIN OF BLOCK EH1 WITH FRAME TITLE comm18.

SELECTION-SCREEN BEGIN OF LINE.
* SELECTION-SCREEN COMMENT 1(4) comm32 MODIF ID R1.
PARAMETERS:rb_dir RADIOBUTTON GROUP dr MODIF ID R1.
SELECTION-SCREEN COMMENT 3(72) comm34 MODIF ID R1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 1(4) comm33 MODIF ID R1.
PARAMETERS:rb_ind RADIOBUTTON GROUP dr MODIF ID R1 .
SELECTION-SCREEN COMMENT 3(72) comm45 MODIF ID R1.

SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN skip .

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(51) comm19.
SELECT-OPTIONS:  s_partnr   FOR a985-zzpartner2 NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(51) comm24.
SELECT-OPTIONS:  s_reltyp    FOR a985-zzreltyp NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(51) comm20.
SELECT-OPTIONS:  s_member    FOR a985-zzreltyp NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(51) comm22.
SELECT-OPTIONS:  s_memsd2    FOR a985-zzreltyp NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(51) comm23.
SELECT-OPTIONS:  s_memmys    FOR a985-zzreltyp NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(51) comm25.
SELECT-OPTIONS:  s_memlps    FOR a985-zzreltyp NO-EXTENSION NO INTERVALS.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(51) comm21.
SELECT-OPTIONS:  s_prlist FOR a985-pltyp.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(51) comm26.
SELECT-OPTIONS:  s_vlaufk FOR a950-zzvlaufk.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK EH1 .


*  *Unwanted
*SELECTION-SCREEN BEGIN OF BLOCK EH WITH FRAME TITLE comm13.
*
*SELECTION-SCREEN BEGIN OF LINE.
*  PARAMETERS:rb_dir RADIOBUTTON GROUP soc  USER-COMMAND ucom1.
*  SELECTION-SCREEN COMMENT 3(72) comm1 .
*SELECTION-SCREEN END OF LINE.
*
*
*SELECTION-SCREEN BEGIN OF LINE.
* SELECTION-SCREEN COMMENT 3(4) comm9 MODIF ID R1.
*PARAMETERS:rb_a937 RADIOBUTTON GROUP dr MODIF ID R1.
*SELECTION-SCREEN COMMENT 10(72) comm3 MODIF ID R1.
*SELECTION-SCREEN END OF LINE.
*
*SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(4) comm10 MODIF ID R1.
*PARAMETERS:rb_a940 RADIOBUTTON GROUP dr MODIF ID R1 .
*SELECTION-SCREEN COMMENT 10(72) comm4 MODIF ID R1.
*SELECTION-SCREEN END OF LINE.
*
*SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(4) comm11 MODIF ID R1.
*PARAMETERS:rb_a950 RADIOBUTTON GROUP dr MODIF ID R1 .
*SELECTION-SCREEN COMMENT 10(72) comm5 MODIF ID R1.
*SELECTION-SCREEN END OF LINE.
*
*
*SELECTION-SCREEN BEGIN OF LINE.
*  PARAMETERS:rb_ind RADIOBUTTON GROUP soc .
*  SELECTION-SCREEN COMMENT 3(72) comm2.
*SELECTION-SCREEN END OF LINE.
*
*
*SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(4) comm12 MODIF ID R2.
*PARAMETERS:rb_in950 RADIOBUTTON GROUP in MODIF ID R2.
*SELECTION-SCREEN COMMENT 10(72) comm6 MODIF ID R2.
*SELECTION-SCREEN END OF LINE.
*
*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS:rb_temp RADIOBUTTON GROUP in MODIF ID R3 .
*SELECTION-SCREEN COMMENT 10(72) comm7 MODIF ID R3.
*SELECTION-SCREEN END OF LINE.
*SELECTION-SCREEN END   OF BLOCK EH.
ENDENHANCEMENT.
