*&---------------------------------------------------------------------*
*&  Include           ZQTCN_CCDUP_TOP
*&---------------------------------------------------------------------*
TABLES:bsegc.
TYPES:BEGIN OF ty_client,

        locid	       TYPE	string,
        currcode     TYPE string,
        fundate	     TYPE	string,
        extmid       TYPE string,
        dbaname	     TYPE	string,
        terminal     TYPE string,
        batchnum     TYPE string,
        batchseqnum	 TYPE	string,
        invoice	     TYPE	string,
        trdate       TYPE string,
        subdate	     TYPE	string,
        cardtype     TYPE string,
        cardnumber   TYPE string,
        pstatus      TYPE string,
        trans_amt	   TYPE	string,
        trans_type   TYPE string,
        trans_status TYPE string,
        pos_mode     TYPE string,
        pos_descr	   TYPE	string,
        authcode     TYPE char10,
        sapdoc       TYPE char10,
        sapcust	     TYPE	char10,
        sapdupsheet	 TYPE	string,
        code1        TYPE string,
        servicecode	 TYPE	string,
        auth_trtype	 TYPE	string,
        plancode     TYPE string,
        plan_descr   TYPE string,
        debitnwid	   TYPE	string,
        rejectreas   TYPE string,
        track_numb   TYPE string,
        order_num	   TYPE	string,
        tr_class     TYPE string,
        mobile_ind   TYPE string,
        elec_commind TYPE string,
        amt          TYPE char20,

      END OF ty_client.


TYPES: BEGIN OF ty_wpay,
         orderid       TYPE  string,
         settype       TYPE  string,
         trdate        TYPE  string,
         tstamp        TYPE  string,
         setstatus     TYPE  string,
         setstreason   TYPE  string,
         setdate       TYPE  string,
         trans_amt     TYPE  string,
         currcode      TYPE  string,
         set_amt       TYPE  string,
         setamt_curr   TYPE  string,
         tr_src        TYPE  string,
         pay_method    TYPE  string,
         cardtype      TYPE  string,
         cardnumber    TYPE  string,
         issu_bank     TYPE  string,
         bank_country  TYPE  string,
         provider      TYPE  string,
         prov_path     TYPE  string,
         trid          TYPE  string,
         arn           TYPE  string,
         fun_trid      TYPE  string,
         authcode      TYPE  char10,
         auth_method   TYPE  string,
         cvv2          TYPE  string,
         avs           TYPE  string,
         term_typ      TYPE  string,
         termid        TYPE  string,
         entry_meth    TYPE  string,
         bu_path       TYPE  string,
         compid        TYPE  string,
         mid           TYPE  string,
         mcc           TYPE  string,
         recp_numb     TYPE  string,
         al_tick_num   TYPE  string,
         fund_trgrp    TYPE  string,
         prov_cvv2     TYPE  string,
         prov_avs      TYPE  string,
         storeid       TYPE  string,
         bill_descr    TYPE  string,
         term_country  TYPE  string,
         term_city     TYPE  string,
         termi_model   TYPE  string,
         iin           TYPE  string,
         last4         TYPE  string,
         bank_st_narr  TYPE  string,
         digi_wall     TYPE  string,
         ord_amt       TYPE  string,
         ord_amt_curr  TYPE  string,
         cashback_amt  TYPE  string,
         cashback_curr TYPE  string,
         dona_amt      TYPE  string,
         dona_curr     TYPE  string,
         grat_amt      TYPE  string,
         grat_amt_curr TYPE  string,
         repogrp       TYPE  string,
         accp_dat      TYPE  string,
         est_date      TYPE  string,
         sch_refid     TYPE  string,
         amt           TYPE  char20,

       END OF ty_wpay,

       BEGIN OF ty_amex,
         trdate     TYPE  string,
         settl_date TYPE  string,
         merch_numb TYPE  string,
         trans_amt  TYPE  string,
         locid      TYPE  string,
         cardnumber TYPE  char25,
         adj_type   TYPE  string,
         charge_ref TYPE  string,
         auth_type  TYPE  string,
         authcode   TYPE  char10,
         type       TYPE  string,


       END OF ty_amex.

TYPES:BEGIN OF ty_output,

        locid         TYPE  string,
        currcode      TYPE string,
        fundate       TYPE  string,
        extmid        TYPE string,
        dbaname       TYPE  string,
        terminal      TYPE string,
        batchnum      TYPE string,
        batchseqnum   TYPE  string,
        invoice       TYPE  string,
        trdate        TYPE string,
        subdate       TYPE  string,
        cardtype      TYPE string,
        cardnumber    TYPE string,
        pstatus       TYPE string,
        trans_amt     TYPE  string,
        trans_type    TYPE string,
        trans_status  TYPE string,
        pos_mode      TYPE string,
        pos_descr     TYPE  string,
        authcode      TYPE char10,
        sapdoc        TYPE char10,
        sapcust       TYPE  char10,
        sapdupsheet   TYPE  string,
        code1         TYPE string,
        servicecode   TYPE  string,
        auth_trtype   TYPE  string,
        plancode      TYPE string,
        plan_descr    TYPE string,
        debitnwid     TYPE  string,
        rejectreas    TYPE string,
        track_numb    TYPE string,
        order_num     TYPE  string,
        tr_class      TYPE string,
        mobile_ind    TYPE string,
        elec_commind  TYPE string,
        dupli_pay(10) TYPE c,

        name1         TYPE ad_name1,
        email         TYPE char40,
        land1         TYPE land1,
        tel_number    TYPE  ad_tlnmbr1,
        city1	        TYPE ad_city1,
        street        TYPE  ad_street,
        str_suppl1    TYPE  ad_strspp1,
        str_suppl2    TYPE  ad_strspp2,

*         trdate     TYPE  string,
        settl_date    TYPE  string,
        merch_numb    TYPE  string,
*         trans_amt TYPE  string,
*         locid     TYPE  string,
*         cardnumber  TYPE  char25,
        adj_type      TYPE  string,
        charge_ref    TYPE  string,
        auth_type     TYPE  string,
*         authcode  TYPE  char10,
        type          TYPE  string,

*wpay
        orderid       TYPE  string,
        settype       TYPE  string,
*        trdate        TYPE  string,
        tstamp        TYPE  string,
        setstatus     TYPE  string,
        setstreason   TYPE  string,
        setdate       TYPE  string,
*        trans_amt     TYPE  string,
*        currcode      TYPE  string,
        set_amt       TYPE  string,
        setamt_curr   TYPE  string,
        tr_src        TYPE  string,
        pay_method    TYPE  string,
*        cardtype      TYPE  string,
*        cardnumber    TYPE  string,
        issu_bank     TYPE  string,
        bank_country  TYPE  string,
        provider      TYPE  string,
        prov_path     TYPE  string,
        trid          TYPE  string,
        arn           TYPE  string,
        fun_trid      TYPE  string,
*        authcode      TYPE  char10,
        auth_method   TYPE  string,
        cvv2          TYPE  string,
        avs           TYPE  string,
        term_typ      TYPE  string,
        termid        TYPE  string,
        entry_meth    TYPE  string,
        bu_path       TYPE  string,
        compid        TYPE  string,
        mid           TYPE  string,
        mcc           TYPE  string,
        recp_numb     TYPE  string,
        al_tick_num   TYPE  string,
        fund_trgrp    TYPE  string,
        prov_cvv2     TYPE  string,
        prov_avs      TYPE  string,
        storeid       TYPE  string,
        bill_descr    TYPE  string,
        term_country  TYPE  string,
        term_city     TYPE  string,
        termi_model   TYPE  string,
        iin           TYPE  string,
        last4         TYPE  string,
        bank_st_narr  TYPE  string,
        digi_wall     TYPE  string,
        ord_amt       TYPE  string,
        ord_amt_curr  TYPE  string,
        cashback_amt  TYPE  string,
        cashback_curr TYPE  string,
        dona_amt      TYPE  string,
        dona_curr     TYPE  string,
        grat_amt      TYPE  string,
        grat_amt_curr TYPE  string,
        repogrp       TYPE  string,
        accp_dat      TYPE  string,
        est_date      TYPE  string,
        sch_refid     TYPE  string,
        amt           TYPE  char20,
      END OF ty_output.

TYPES:
  t_fieldcat TYPE slis_fieldcat_alv,
  t_layout   TYPE slis_layout_alv.


DATA:i_client   TYPE STANDARD TABLE OF ty_client,
     i_wpay     TYPE STANDARD TABLE OF ty_wpay,
     i_amex     TYPE STANDARD TABLE OF ty_amex,
     i_output   TYPE STANDARD TABLE OF ty_output,
     wa_output  TYPE  ty_output,
     wa_client  TYPE ty_client,
     wa_wpay    TYPE ty_wpay,
     wa_amex    TYPE ty_amex,
     w_fieldcat TYPE t_fieldcat,
     w_layout   TYPE t_layout,
     i_fieldcat TYPE STANDARD TABLE OF t_fieldcat.
