*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_MEMB_DUE..................................*
FORM GET_DATA_ZQTCV_MEMB_DUE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_MEMB_DUE WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_MEMB_DUE .
ZQTCV_MEMB_DUE-MANDT =
ZQTC_MEMB_DUE-MANDT .
ZQTCV_MEMB_DUE-EXTWG =
ZQTC_MEMB_DUE-EXTWG .
ZQTCV_MEMB_DUE-AENAM =
ZQTC_MEMB_DUE-AENAM .
ZQTCV_MEMB_DUE-AEDAT =
ZQTC_MEMB_DUE-AEDAT .
ZQTCV_MEMB_DUE-AEZET =
ZQTC_MEMB_DUE-AEZET .
    SELECT SINGLE * FROM TWEW WHERE
EXTWG = ZQTC_MEMB_DUE-EXTWG .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TWEWT WHERE
EXTWG = TWEW-EXTWG AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_MEMB_DUE-EWBEZ =
TWEWT-EWBEZ .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_MEMB_DUE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_MEMB_DUE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_MEMB_DUE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_MEMB_DUE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_MEMB_DUE WHERE
  EXTWG = ZQTCV_MEMB_DUE-EXTWG .
    IF SY-SUBRC = 0.
    DELETE ZQTC_MEMB_DUE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_MEMB_DUE WHERE
  EXTWG = ZQTCV_MEMB_DUE-EXTWG .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_MEMB_DUE.
    ENDIF.
ZQTC_MEMB_DUE-MANDT =
ZQTCV_MEMB_DUE-MANDT .
ZQTC_MEMB_DUE-EXTWG =
ZQTCV_MEMB_DUE-EXTWG .
ZQTC_MEMB_DUE-AENAM =
ZQTCV_MEMB_DUE-AENAM .
ZQTC_MEMB_DUE-AEDAT =
ZQTCV_MEMB_DUE-AEDAT .
ZQTC_MEMB_DUE-AEZET =
ZQTCV_MEMB_DUE-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_MEMB_DUE .
    ELSE.
    INSERT ZQTC_MEMB_DUE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_MEMB_DUE-UPD_FLAG,
STATUS_ZQTCV_MEMB_DUE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_MEMB_DUE.
  SELECT SINGLE * FROM ZQTC_MEMB_DUE WHERE
EXTWG = ZQTCV_MEMB_DUE-EXTWG .
ZQTCV_MEMB_DUE-MANDT =
ZQTC_MEMB_DUE-MANDT .
ZQTCV_MEMB_DUE-EXTWG =
ZQTC_MEMB_DUE-EXTWG .
ZQTCV_MEMB_DUE-AENAM =
ZQTC_MEMB_DUE-AENAM .
ZQTCV_MEMB_DUE-AEDAT =
ZQTC_MEMB_DUE-AEDAT .
ZQTCV_MEMB_DUE-AEZET =
ZQTC_MEMB_DUE-AEZET .
    SELECT SINGLE * FROM TWEW WHERE
EXTWG = ZQTC_MEMB_DUE-EXTWG .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TWEWT WHERE
EXTWG = TWEW-EXTWG AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_MEMB_DUE-EWBEZ =
TWEWT-EWBEZ .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_MEMB_DUE-EWBEZ .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_MEMB_DUE-EWBEZ .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_MEMB_DUE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_MEMB_DUE-EXTWG TO
ZQTC_MEMB_DUE-EXTWG .
MOVE ZQTCV_MEMB_DUE-MANDT TO
ZQTC_MEMB_DUE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_MEMB_DUE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_MEMB_DUE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_MEMB_DUE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZQTCV_MEMB_DUE USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZQTC_MEMB_DUE-MANDT =
ZQTCV_MEMB_DUE-MANDT .
ZQTC_MEMB_DUE-EXTWG =
ZQTCV_MEMB_DUE-EXTWG .
ZQTC_MEMB_DUE-AENAM =
ZQTCV_MEMB_DUE-AENAM .
ZQTC_MEMB_DUE-AEDAT =
ZQTCV_MEMB_DUE-AEDAT .
ZQTC_MEMB_DUE-AEZET =
ZQTCV_MEMB_DUE-AEZET .
    SELECT SINGLE * FROM TWEW WHERE
EXTWG = ZQTC_MEMB_DUE-EXTWG .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TWEWT WHERE
EXTWG = TWEW-EXTWG AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_MEMB_DUE-EWBEZ =
TWEWT-EWBEZ .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_MEMB_DUE-EWBEZ .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_MEMB_DUE-EWBEZ .
    ENDIF.
ENDFORM.
