*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_PRINT_VEND................................*
FORM GET_DATA_ZQTCV_PRINT_VEND.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_PRINT_VEND WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_PRINT_VEND .
ZQTCV_PRINT_VEND-MANDT =
ZQTC_PRINT_VEND-MANDT .
ZQTCV_PRINT_VEND-BUS_PRCOCESS =
ZQTC_PRINT_VEND-BUS_PRCOCESS .
ZQTCV_PRINT_VEND-COUNTRY =
ZQTC_PRINT_VEND-COUNTRY .
ZQTCV_PRINT_VEND-OUTPUT_TYPE =
ZQTC_PRINT_VEND-OUTPUT_TYPE .
ZQTCV_PRINT_VEND-PRINT_VENDOR =
ZQTC_PRINT_VEND-PRINT_VENDOR .
ZQTCV_PRINT_VEND-PRINT_REGION =
ZQTC_PRINT_VEND-PRINT_REGION .
ZQTCV_PRINT_VEND-COUNTRY_SORT =
ZQTC_PRINT_VEND-COUNTRY_SORT .
ZQTCV_PRINT_VEND-FILE_LOC =
ZQTC_PRINT_VEND-FILE_LOC .
ZQTCV_PRINT_VEND-AENAM =
ZQTC_PRINT_VEND-AENAM .
ZQTCV_PRINT_VEND-AEDAT =
ZQTC_PRINT_VEND-AEDAT .
ZQTCV_PRINT_VEND-AEZET =
ZQTC_PRINT_VEND-AEZET .
<VIM_TOTAL_STRUC> = ZQTCV_PRINT_VEND.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_PRINT_VEND .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_PRINT_VEND.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_PRINT_VEND-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_PRINT_VEND WHERE
  BUS_PRCOCESS = ZQTCV_PRINT_VEND-BUS_PRCOCESS AND
  COUNTRY = ZQTCV_PRINT_VEND-COUNTRY AND
  OUTPUT_TYPE = ZQTCV_PRINT_VEND-OUTPUT_TYPE .
    IF SY-SUBRC = 0.
    DELETE ZQTC_PRINT_VEND .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_PRINT_VEND WHERE
  BUS_PRCOCESS = ZQTCV_PRINT_VEND-BUS_PRCOCESS AND
  COUNTRY = ZQTCV_PRINT_VEND-COUNTRY AND
  OUTPUT_TYPE = ZQTCV_PRINT_VEND-OUTPUT_TYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_PRINT_VEND.
    ENDIF.
ZQTC_PRINT_VEND-MANDT =
ZQTCV_PRINT_VEND-MANDT .
ZQTC_PRINT_VEND-BUS_PRCOCESS =
ZQTCV_PRINT_VEND-BUS_PRCOCESS .
ZQTC_PRINT_VEND-COUNTRY =
ZQTCV_PRINT_VEND-COUNTRY .
ZQTC_PRINT_VEND-OUTPUT_TYPE =
ZQTCV_PRINT_VEND-OUTPUT_TYPE .
ZQTC_PRINT_VEND-PRINT_VENDOR =
ZQTCV_PRINT_VEND-PRINT_VENDOR .
ZQTC_PRINT_VEND-PRINT_REGION =
ZQTCV_PRINT_VEND-PRINT_REGION .
ZQTC_PRINT_VEND-COUNTRY_SORT =
ZQTCV_PRINT_VEND-COUNTRY_SORT .
ZQTC_PRINT_VEND-FILE_LOC =
ZQTCV_PRINT_VEND-FILE_LOC .
ZQTC_PRINT_VEND-AENAM =
ZQTCV_PRINT_VEND-AENAM .
ZQTC_PRINT_VEND-AEDAT =
ZQTCV_PRINT_VEND-AEDAT .
ZQTC_PRINT_VEND-AEZET =
ZQTCV_PRINT_VEND-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_PRINT_VEND .
    ELSE.
    INSERT ZQTC_PRINT_VEND .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_PRINT_VEND-UPD_FLAG,
STATUS_ZQTCV_PRINT_VEND-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_PRINT_VEND.
  SELECT SINGLE * FROM ZQTC_PRINT_VEND WHERE
BUS_PRCOCESS = ZQTCV_PRINT_VEND-BUS_PRCOCESS AND
COUNTRY = ZQTCV_PRINT_VEND-COUNTRY AND
OUTPUT_TYPE = ZQTCV_PRINT_VEND-OUTPUT_TYPE .
ZQTCV_PRINT_VEND-MANDT =
ZQTC_PRINT_VEND-MANDT .
ZQTCV_PRINT_VEND-BUS_PRCOCESS =
ZQTC_PRINT_VEND-BUS_PRCOCESS .
ZQTCV_PRINT_VEND-COUNTRY =
ZQTC_PRINT_VEND-COUNTRY .
ZQTCV_PRINT_VEND-OUTPUT_TYPE =
ZQTC_PRINT_VEND-OUTPUT_TYPE .
ZQTCV_PRINT_VEND-PRINT_VENDOR =
ZQTC_PRINT_VEND-PRINT_VENDOR .
ZQTCV_PRINT_VEND-PRINT_REGION =
ZQTC_PRINT_VEND-PRINT_REGION .
ZQTCV_PRINT_VEND-COUNTRY_SORT =
ZQTC_PRINT_VEND-COUNTRY_SORT .
ZQTCV_PRINT_VEND-FILE_LOC =
ZQTC_PRINT_VEND-FILE_LOC .
ZQTCV_PRINT_VEND-AENAM =
ZQTC_PRINT_VEND-AENAM .
ZQTCV_PRINT_VEND-AEDAT =
ZQTC_PRINT_VEND-AEDAT .
ZQTCV_PRINT_VEND-AEZET =
ZQTC_PRINT_VEND-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_PRINT_VEND USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_PRINT_VEND-BUS_PRCOCESS TO
ZQTC_PRINT_VEND-BUS_PRCOCESS .
MOVE ZQTCV_PRINT_VEND-COUNTRY TO
ZQTC_PRINT_VEND-COUNTRY .
MOVE ZQTCV_PRINT_VEND-OUTPUT_TYPE TO
ZQTC_PRINT_VEND-OUTPUT_TYPE .
MOVE ZQTCV_PRINT_VEND-MANDT TO
ZQTC_PRINT_VEND-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_PRINT_VEND'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_PRINT_VEND TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_PRINT_VEND'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
