*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_REL_CAT...................................*
FORM GET_DATA_ZQTCV_REL_CAT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_RELATIONCAT WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_REL_CAT .
ZQTCV_REL_CAT-MANDT =
ZQTC_RELATIONCAT-MANDT .
ZQTCV_REL_CAT-RELTYP =
ZQTC_RELATIONCAT-RELTYP .
ZQTCV_REL_CAT-KDKG2 =
ZQTC_RELATIONCAT-KDKG2 .
ZQTCV_REL_CAT-KONDA =
ZQTC_RELATIONCAT-KONDA .
    SELECT * FROM TBZ9 WHERE
RELTYP = ZQTC_RELATIONCAT-RELTYP .
      SELECT SINGLE * FROM TBZ9A WHERE
RELTYP = TBZ9-RELTYP AND
XRF = TBZ9-XRF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_REL_CAT-BEZ50 =
TBZ9A-BEZ50 .
      ENDIF.
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZQTCV_REL_CAT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_REL_CAT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_REL_CAT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_REL_CAT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RELATIONCAT WHERE
  RELTYP = ZQTCV_REL_CAT-RELTYP .
    IF SY-SUBRC = 0.
    DELETE ZQTC_RELATIONCAT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RELATIONCAT WHERE
  RELTYP = ZQTCV_REL_CAT-RELTYP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_RELATIONCAT.
    ENDIF.
ZQTC_RELATIONCAT-MANDT =
ZQTCV_REL_CAT-MANDT .
ZQTC_RELATIONCAT-RELTYP =
ZQTCV_REL_CAT-RELTYP .
ZQTC_RELATIONCAT-KDKG2 =
ZQTCV_REL_CAT-KDKG2 .
ZQTC_RELATIONCAT-KONDA =
ZQTCV_REL_CAT-KONDA .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_RELATIONCAT .
    ELSE.
    INSERT ZQTC_RELATIONCAT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_REL_CAT-UPD_FLAG,
STATUS_ZQTCV_REL_CAT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_REL_CAT.
  SELECT SINGLE * FROM ZQTC_RELATIONCAT WHERE
RELTYP = ZQTCV_REL_CAT-RELTYP .
ZQTCV_REL_CAT-MANDT =
ZQTC_RELATIONCAT-MANDT .
ZQTCV_REL_CAT-RELTYP =
ZQTC_RELATIONCAT-RELTYP .
ZQTCV_REL_CAT-KDKG2 =
ZQTC_RELATIONCAT-KDKG2 .
ZQTCV_REL_CAT-KONDA =
ZQTC_RELATIONCAT-KONDA .
    SELECT * FROM TBZ9 WHERE
RELTYP = ZQTC_RELATIONCAT-RELTYP .
      SELECT SINGLE * FROM TBZ9A WHERE
RELTYP = TBZ9-RELTYP AND
XRF = TBZ9-XRF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_REL_CAT-BEZ50 =
TBZ9A-BEZ50 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_REL_CAT-BEZ50 .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_REL_CAT-BEZ50 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_REL_CAT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_REL_CAT-RELTYP TO
ZQTC_RELATIONCAT-RELTYP .
MOVE ZQTCV_REL_CAT-MANDT TO
ZQTC_RELATIONCAT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_RELATIONCAT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_RELATIONCAT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_RELATIONCAT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZQTCV_REL_CAT USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZQTC_RELATIONCAT-MANDT =
ZQTCV_REL_CAT-MANDT .
ZQTC_RELATIONCAT-RELTYP =
ZQTCV_REL_CAT-RELTYP .
ZQTC_RELATIONCAT-KDKG2 =
ZQTCV_REL_CAT-KDKG2 .
ZQTC_RELATIONCAT-KONDA =
ZQTCV_REL_CAT-KONDA .
    SELECT * FROM TBZ9 WHERE
RELTYP = ZQTC_RELATIONCAT-RELTYP .
      SELECT SINGLE * FROM TBZ9A WHERE
RELTYP = TBZ9-RELTYP AND
XRF = TBZ9-XRF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_REL_CAT-BEZ50 =
TBZ9A-BEZ50 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_REL_CAT-BEZ50 .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_REL_CAT-BEZ50 .
    ENDIF.
ENDFORM.
