*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_RENWL_PDET................................*
FORM GET_DATA_ZQTCV_RENWL_PDET.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_RENWL_P_DET WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_RENWL_PDET .
ZQTCV_RENWL_PDET-MANDT =
ZQTC_RENWL_P_DET-MANDT .
ZQTCV_RENWL_PDET-RENWL_PROF =
ZQTC_RENWL_P_DET-RENWL_PROF .
ZQTCV_RENWL_PDET-QUOTE_TIME =
ZQTC_RENWL_P_DET-QUOTE_TIME .
ZQTCV_RENWL_PDET-NOTIF_PROF =
ZQTC_RENWL_P_DET-NOTIF_PROF .
ZQTCV_RENWL_PDET-GRACE_START =
ZQTC_RENWL_P_DET-GRACE_START .
ZQTCV_RENWL_PDET-GRACE_PERIOD =
ZQTC_RENWL_P_DET-GRACE_PERIOD .
ZQTCV_RENWL_PDET-AUTO_RENEW =
ZQTC_RENWL_P_DET-AUTO_RENEW .
ZQTCV_RENWL_PDET-LAPSE =
ZQTC_RENWL_P_DET-LAPSE .
ZQTCV_RENWL_PDET-CONSOLIDATE =
ZQTC_RENWL_P_DET-CONSOLIDATE .
ZQTCV_RENWL_PDET-AENAM =
ZQTC_RENWL_P_DET-AENAM .
ZQTCV_RENWL_PDET-AEDAT =
ZQTC_RENWL_P_DET-AEDAT .
ZQTCV_RENWL_PDET-AEZET =
ZQTC_RENWL_P_DET-AEZET .
    SELECT SINGLE * FROM ZQTC_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_RENWL_P_DET-NOTIF_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PDET-NOTIF_PROF_D =
ZQTCT_NOTIF_PROF-NOTIF_PROF_D .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_P_DET-RENWL_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PDET-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_RENWL_PDET.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_RENWL_PDET .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_RENWL_PDET.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_RENWL_PDET-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RENWL_P_DET WHERE
  RENWL_PROF = ZQTCV_RENWL_PDET-RENWL_PROF .
    IF SY-SUBRC = 0.
    DELETE ZQTC_RENWL_P_DET .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RENWL_P_DET WHERE
  RENWL_PROF = ZQTCV_RENWL_PDET-RENWL_PROF .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_RENWL_P_DET.
    ENDIF.
ZQTC_RENWL_P_DET-MANDT =
ZQTCV_RENWL_PDET-MANDT .
ZQTC_RENWL_P_DET-RENWL_PROF =
ZQTCV_RENWL_PDET-RENWL_PROF .
ZQTC_RENWL_P_DET-QUOTE_TIME =
ZQTCV_RENWL_PDET-QUOTE_TIME .
ZQTC_RENWL_P_DET-NOTIF_PROF =
ZQTCV_RENWL_PDET-NOTIF_PROF .
ZQTC_RENWL_P_DET-GRACE_START =
ZQTCV_RENWL_PDET-GRACE_START .
ZQTC_RENWL_P_DET-GRACE_PERIOD =
ZQTCV_RENWL_PDET-GRACE_PERIOD .
ZQTC_RENWL_P_DET-AUTO_RENEW =
ZQTCV_RENWL_PDET-AUTO_RENEW .
ZQTC_RENWL_P_DET-LAPSE =
ZQTCV_RENWL_PDET-LAPSE .
ZQTC_RENWL_P_DET-CONSOLIDATE =
ZQTCV_RENWL_PDET-CONSOLIDATE .
ZQTC_RENWL_P_DET-AENAM =
ZQTCV_RENWL_PDET-AENAM .
ZQTC_RENWL_P_DET-AEDAT =
ZQTCV_RENWL_PDET-AEDAT .
ZQTC_RENWL_P_DET-AEZET =
ZQTCV_RENWL_PDET-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_RENWL_P_DET .
    ELSE.
    INSERT ZQTC_RENWL_P_DET .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_RENWL_PDET-UPD_FLAG,
STATUS_ZQTCV_RENWL_PDET-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_RENWL_PDET.
  SELECT SINGLE * FROM ZQTC_RENWL_P_DET WHERE
RENWL_PROF = ZQTCV_RENWL_PDET-RENWL_PROF .
ZQTCV_RENWL_PDET-MANDT =
ZQTC_RENWL_P_DET-MANDT .
ZQTCV_RENWL_PDET-RENWL_PROF =
ZQTC_RENWL_P_DET-RENWL_PROF .
ZQTCV_RENWL_PDET-QUOTE_TIME =
ZQTC_RENWL_P_DET-QUOTE_TIME .
ZQTCV_RENWL_PDET-NOTIF_PROF =
ZQTC_RENWL_P_DET-NOTIF_PROF .
ZQTCV_RENWL_PDET-GRACE_START =
ZQTC_RENWL_P_DET-GRACE_START .
ZQTCV_RENWL_PDET-GRACE_PERIOD =
ZQTC_RENWL_P_DET-GRACE_PERIOD .
ZQTCV_RENWL_PDET-AUTO_RENEW =
ZQTC_RENWL_P_DET-AUTO_RENEW .
ZQTCV_RENWL_PDET-LAPSE =
ZQTC_RENWL_P_DET-LAPSE .
ZQTCV_RENWL_PDET-CONSOLIDATE =
ZQTC_RENWL_P_DET-CONSOLIDATE .
ZQTCV_RENWL_PDET-AENAM =
ZQTC_RENWL_P_DET-AENAM .
ZQTCV_RENWL_PDET-AEDAT =
ZQTC_RENWL_P_DET-AEDAT .
ZQTCV_RENWL_PDET-AEZET =
ZQTC_RENWL_P_DET-AEZET .
    SELECT SINGLE * FROM ZQTC_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_RENWL_P_DET-NOTIF_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PDET-NOTIF_PROF_D =
ZQTCT_NOTIF_PROF-NOTIF_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PDET-NOTIF_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PDET-NOTIF_PROF_D .
    ENDIF.
    SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_P_DET-RENWL_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PDET-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PDET-RENWL_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PDET-RENWL_PROF_D .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_RENWL_PDET USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_RENWL_PDET-RENWL_PROF TO
ZQTC_RENWL_P_DET-RENWL_PROF .
MOVE ZQTCV_RENWL_PDET-MANDT TO
ZQTC_RENWL_P_DET-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_RENWL_P_DET'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_RENWL_P_DET TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_RENWL_P_DET'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZQTCV_RENWL_PDET USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZQTC_RENWL_P_DET-MANDT =
ZQTCV_RENWL_PDET-MANDT .
ZQTC_RENWL_P_DET-RENWL_PROF =
ZQTCV_RENWL_PDET-RENWL_PROF .
ZQTC_RENWL_P_DET-QUOTE_TIME =
ZQTCV_RENWL_PDET-QUOTE_TIME .
ZQTC_RENWL_P_DET-NOTIF_PROF =
ZQTCV_RENWL_PDET-NOTIF_PROF .
ZQTC_RENWL_P_DET-GRACE_START =
ZQTCV_RENWL_PDET-GRACE_START .
ZQTC_RENWL_P_DET-GRACE_PERIOD =
ZQTCV_RENWL_PDET-GRACE_PERIOD .
ZQTC_RENWL_P_DET-AUTO_RENEW =
ZQTCV_RENWL_PDET-AUTO_RENEW .
ZQTC_RENWL_P_DET-LAPSE =
ZQTCV_RENWL_PDET-LAPSE .
ZQTC_RENWL_P_DET-CONSOLIDATE =
ZQTCV_RENWL_PDET-CONSOLIDATE .
ZQTC_RENWL_P_DET-AENAM =
ZQTCV_RENWL_PDET-AENAM .
ZQTC_RENWL_P_DET-AEDAT =
ZQTCV_RENWL_PDET-AEDAT .
ZQTC_RENWL_P_DET-AEZET =
ZQTCV_RENWL_PDET-AEZET .
    SELECT SINGLE * FROM ZQTC_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_RENWL_P_DET-NOTIF_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PDET-NOTIF_PROF_D =
ZQTCT_NOTIF_PROF-NOTIF_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PDET-NOTIF_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PDET-NOTIF_PROF_D .
    ENDIF.
    SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_P_DET-RENWL_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PDET-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PDET-RENWL_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PDET-RENWL_PROF_D .
    ENDIF.
ENDFORM.
*...processing: ZQTCV_RENWL_PROF................................*
FORM GET_DATA_ZQTCV_RENWL_PROF.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_RENWL_PROF WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_RENWL_PROF .
ZQTCV_RENWL_PROF-MANDT =
ZQTC_RENWL_PROF-MANDT .
ZQTCV_RENWL_PROF-RENWL_PROF =
ZQTC_RENWL_PROF-RENWL_PROF .
ZQTCV_RENWL_PROF-AENAM =
ZQTC_RENWL_PROF-AENAM .
ZQTCV_RENWL_PROF-AEDAT =
ZQTC_RENWL_PROF-AEDAT .
ZQTCV_RENWL_PROF-AEZET =
ZQTC_RENWL_PROF-AEZET .
    SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PROF-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_RENWL_PROF.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_RENWL_PROF .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_RENWL_PROF.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_RENWL_PROF-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RENWL_PROF WHERE
  RENWL_PROF = ZQTCV_RENWL_PROF-RENWL_PROF .
    IF SY-SUBRC = 0.
    DELETE ZQTC_RENWL_PROF .
    ENDIF.
    DELETE FROM ZQTCT_RENWL_PROF WHERE
    RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RENWL_PROF WHERE
  RENWL_PROF = ZQTCV_RENWL_PROF-RENWL_PROF .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_RENWL_PROF.
    ENDIF.
ZQTC_RENWL_PROF-MANDT =
ZQTCV_RENWL_PROF-MANDT .
ZQTC_RENWL_PROF-RENWL_PROF =
ZQTCV_RENWL_PROF-RENWL_PROF .
ZQTC_RENWL_PROF-AENAM =
ZQTCV_RENWL_PROF-AENAM .
ZQTC_RENWL_PROF-AEDAT =
ZQTCV_RENWL_PROF-AEDAT .
ZQTC_RENWL_PROF-AEZET =
ZQTCV_RENWL_PROF-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_RENWL_PROF .
    ELSE.
    INSERT ZQTC_RENWL_PROF .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZQTCT_RENWL_PROF WHERE
    RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZQTCT_RENWL_PROF.
ZQTCT_RENWL_PROF-RENWL_PROF =
ZQTC_RENWL_PROF-RENWL_PROF .
ZQTCT_RENWL_PROF-SPRAS =
SY-LANGU .
      ENDIF.
ZQTCT_RENWL_PROF-RENWL_PROF_D =
ZQTCV_RENWL_PROF-RENWL_PROF_D .
    IF SY-SUBRC = 0.
    UPDATE ZQTCT_RENWL_PROF .
    ELSE.
    INSERT ZQTCT_RENWL_PROF .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_RENWL_PROF-UPD_FLAG,
STATUS_ZQTCV_RENWL_PROF-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_RENWL_PROF.
  SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTCV_RENWL_PROF-RENWL_PROF .
ZQTCV_RENWL_PROF-MANDT =
ZQTC_RENWL_PROF-MANDT .
ZQTCV_RENWL_PROF-RENWL_PROF =
ZQTC_RENWL_PROF-RENWL_PROF .
ZQTCV_RENWL_PROF-AENAM =
ZQTC_RENWL_PROF-AENAM .
ZQTCV_RENWL_PROF-AEDAT =
ZQTC_RENWL_PROF-AEDAT .
ZQTCV_RENWL_PROF-AEZET =
ZQTC_RENWL_PROF-AEZET .
    SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PROF-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PROF-RENWL_PROF_D .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_RENWL_PROF USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_RENWL_PROF-RENWL_PROF TO
ZQTC_RENWL_PROF-RENWL_PROF .
MOVE ZQTCV_RENWL_PROF-MANDT TO
ZQTC_RENWL_PROF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_RENWL_PROF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_RENWL_PROF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_RENWL_PROF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZQTC_RENWL_PROF-RENWL_PROF TO
ZQTCT_RENWL_PROF-RENWL_PROF .
MOVE SY-LANGU TO
ZQTCT_RENWL_PROF-SPRAS .
MOVE ZQTCV_RENWL_PROF-MANDT TO
ZQTCT_RENWL_PROF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTCT_RENWL_PROF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTCT_RENWL_PROF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTCT_RENWL_PROF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
