*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_PUB_TYP_PG................................*
FORM GET_DATA_ZQTCV_PUB_TYP_PG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_PUB_TYP_PG WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_PUB_TYP_PG .
ZQTCV_PUB_TYP_PG-MANDT =
ZQTC_PUB_TYP_PG-MANDT .
ZQTCV_PUB_TYP_PG-PUBLICATION_TYPE =
ZQTC_PUB_TYP_PG-PUBLICATION_TYPE .
ZQTCV_PUB_TYP_PG-PROD_GROUP =
ZQTC_PUB_TYP_PG-PROD_GROUP .
    SELECT SINGLE * FROM TJPPUBTP WHERE
ISMPUBLTYPE = ZQTC_PUB_TYP_PG-PUBLICATION_TYPE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TJPPUBTPT WHERE
ISMPUBLTYPE = TJPPUBTP-ISMPUBLTYPE AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_PUB_TYP_PG-BEZEICHNUNG =
TJPPUBTPT-BEZEICHNUNG .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZQTC_PROD_GROUP WHERE
PROD_GROUP = ZQTC_PUB_TYP_PG-PROD_GROUP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_PROD_GROUP WHERE
PROD_GROUP = ZQTC_PROD_GROUP-PROD_GROUP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_PUB_TYP_PG-PROD_GROUP_D =
ZQTCT_PROD_GROUP-PROD_GROUP_D .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_PUB_TYP_PG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_PUB_TYP_PG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_PUB_TYP_PG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_PUB_TYP_PG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_PUB_TYP_PG WHERE
  PUBLICATION_TYPE = ZQTCV_PUB_TYP_PG-PUBLICATION_TYPE .
    IF SY-SUBRC = 0.
    DELETE ZQTC_PUB_TYP_PG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_PUB_TYP_PG WHERE
  PUBLICATION_TYPE = ZQTCV_PUB_TYP_PG-PUBLICATION_TYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_PUB_TYP_PG.
    ENDIF.
ZQTC_PUB_TYP_PG-MANDT =
ZQTCV_PUB_TYP_PG-MANDT .
ZQTC_PUB_TYP_PG-PUBLICATION_TYPE =
ZQTCV_PUB_TYP_PG-PUBLICATION_TYPE .
ZQTC_PUB_TYP_PG-PROD_GROUP =
ZQTCV_PUB_TYP_PG-PROD_GROUP .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_PUB_TYP_PG .
    ELSE.
    INSERT ZQTC_PUB_TYP_PG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_PUB_TYP_PG-UPD_FLAG,
STATUS_ZQTCV_PUB_TYP_PG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_PUB_TYP_PG.
  SELECT SINGLE * FROM ZQTC_PUB_TYP_PG WHERE
PUBLICATION_TYPE = ZQTCV_PUB_TYP_PG-PUBLICATION_TYPE .
ZQTCV_PUB_TYP_PG-MANDT =
ZQTC_PUB_TYP_PG-MANDT .
ZQTCV_PUB_TYP_PG-PUBLICATION_TYPE =
ZQTC_PUB_TYP_PG-PUBLICATION_TYPE .
ZQTCV_PUB_TYP_PG-PROD_GROUP =
ZQTC_PUB_TYP_PG-PROD_GROUP .
    SELECT SINGLE * FROM TJPPUBTP WHERE
ISMPUBLTYPE = ZQTC_PUB_TYP_PG-PUBLICATION_TYPE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TJPPUBTPT WHERE
ISMPUBLTYPE = TJPPUBTP-ISMPUBLTYPE AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_PUB_TYP_PG-BEZEICHNUNG =
TJPPUBTPT-BEZEICHNUNG .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_PUB_TYP_PG-BEZEICHNUNG .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_PUB_TYP_PG-BEZEICHNUNG .
    ENDIF.
    SELECT SINGLE * FROM ZQTC_PROD_GROUP WHERE
PROD_GROUP = ZQTC_PUB_TYP_PG-PROD_GROUP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_PROD_GROUP WHERE
PROD_GROUP = ZQTC_PROD_GROUP-PROD_GROUP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_PUB_TYP_PG-PROD_GROUP_D =
ZQTCT_PROD_GROUP-PROD_GROUP_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_PUB_TYP_PG-PROD_GROUP_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_PUB_TYP_PG-PROD_GROUP_D .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_PUB_TYP_PG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_PUB_TYP_PG-PUBLICATION_TYPE TO
ZQTC_PUB_TYP_PG-PUBLICATION_TYPE .
MOVE ZQTCV_PUB_TYP_PG-MANDT TO
ZQTC_PUB_TYP_PG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_PUB_TYP_PG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_PUB_TYP_PG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_PUB_TYP_PG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZQTCV_PUB_TYP_PG USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZQTC_PUB_TYP_PG-MANDT =
ZQTCV_PUB_TYP_PG-MANDT .
ZQTC_PUB_TYP_PG-PUBLICATION_TYPE =
ZQTCV_PUB_TYP_PG-PUBLICATION_TYPE .
ZQTC_PUB_TYP_PG-PROD_GROUP =
ZQTCV_PUB_TYP_PG-PROD_GROUP .
    SELECT SINGLE * FROM TJPPUBTP WHERE
ISMPUBLTYPE = ZQTC_PUB_TYP_PG-PUBLICATION_TYPE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TJPPUBTPT WHERE
ISMPUBLTYPE = TJPPUBTP-ISMPUBLTYPE AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_PUB_TYP_PG-BEZEICHNUNG =
TJPPUBTPT-BEZEICHNUNG .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_PUB_TYP_PG-BEZEICHNUNG .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_PUB_TYP_PG-BEZEICHNUNG .
    ENDIF.
    SELECT SINGLE * FROM ZQTC_PROD_GROUP WHERE
PROD_GROUP = ZQTC_PUB_TYP_PG-PROD_GROUP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_PROD_GROUP WHERE
PROD_GROUP = ZQTC_PROD_GROUP-PROD_GROUP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_PUB_TYP_PG-PROD_GROUP_D =
ZQTCT_PROD_GROUP-PROD_GROUP_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_PUB_TYP_PG-PROD_GROUP_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_PUB_TYP_PG-PROD_GROUP_D .
    ENDIF.
ENDFORM.
