*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZQTCV_NOTIF_OUT.................................*
TABLES: ZQTCV_NOTIF_OUT, *ZQTCV_NOTIF_OUT. "view work areas
CONTROLS: TCTRL_ZQTCV_NOTIF_OUT
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZQTCV_NOTIF_OUT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZQTCV_NOTIF_OUT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZQTCV_NOTIF_OUT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZQTCV_NOTIF_OUT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZQTCV_NOTIF_OUT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZQTCV_NOTIF_OUT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZQTCV_NOTIF_OUT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZQTCV_NOTIF_OUT_TOTAL.

*...processing: ZQTCV_NOTIF_PDET................................*
TABLES: ZQTCV_NOTIF_PDET, *ZQTCV_NOTIF_PDET. "view work areas
CONTROLS: TCTRL_ZQTCV_NOTIF_PDET
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZQTCV_NOTIF_PDET. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZQTCV_NOTIF_PDET.
* Table for entries selected to show on screen
DATA: BEGIN OF ZQTCV_NOTIF_PDET_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZQTCV_NOTIF_PDET.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZQTCV_NOTIF_PDET_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZQTCV_NOTIF_PDET_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZQTCV_NOTIF_PDET.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZQTCV_NOTIF_PDET_TOTAL.

*...processing: ZQTCV_NOTIF_PROF................................*
TABLES: ZQTCV_NOTIF_PROF, *ZQTCV_NOTIF_PROF. "view work areas
CONTROLS: TCTRL_ZQTCV_NOTIF_PROF
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZQTCV_NOTIF_PROF. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZQTCV_NOTIF_PROF.
* Table for entries selected to show on screen
DATA: BEGIN OF ZQTCV_NOTIF_PROF_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZQTCV_NOTIF_PROF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZQTCV_NOTIF_PROF_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZQTCV_NOTIF_PROF_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZQTCV_NOTIF_PROF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZQTCV_NOTIF_PROF_TOTAL.

*.........table declarations:.................................*
TABLES: T685                           .
TABLES: T685T                          .
TABLES: ZQTCT_NOTIF_PROF               .
TABLES: ZQTC_NOTIF_OUTPT               .
TABLES: ZQTC_NOTIF_PROF                .
TABLES: ZQTC_NOTIF_P_DET               .
