*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_DET_COSTC.................................*
FORM GET_DATA_ZQTCV_DET_COSTC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_DETRM_COSTC WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_DET_COSTC .
ZQTCV_DET_COSTC-MANDT =
ZQTC_DETRM_COSTC-MANDT .
ZQTCV_DET_COSTC-EXTWG =
ZQTC_DETRM_COSTC-EXTWG .
ZQTCV_DET_COSTC-WERKS =
ZQTC_DETRM_COSTC-WERKS .
ZQTCV_DET_COSTC-KOSTL =
ZQTC_DETRM_COSTC-KOSTL .
ZQTCV_DET_COSTC-AENAM =
ZQTC_DETRM_COSTC-AENAM .
ZQTCV_DET_COSTC-AEDAT =
ZQTC_DETRM_COSTC-AEDAT .
ZQTCV_DET_COSTC-AEZET =
ZQTC_DETRM_COSTC-AEZET .
<VIM_TOTAL_STRUC> = ZQTCV_DET_COSTC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_DET_COSTC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_DET_COSTC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_DET_COSTC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_DETRM_COSTC WHERE
  EXTWG = ZQTCV_DET_COSTC-EXTWG AND
  WERKS = ZQTCV_DET_COSTC-WERKS .
    IF SY-SUBRC = 0.
    DELETE ZQTC_DETRM_COSTC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_DETRM_COSTC WHERE
  EXTWG = ZQTCV_DET_COSTC-EXTWG AND
  WERKS = ZQTCV_DET_COSTC-WERKS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_DETRM_COSTC.
    ENDIF.
ZQTC_DETRM_COSTC-MANDT =
ZQTCV_DET_COSTC-MANDT .
ZQTC_DETRM_COSTC-EXTWG =
ZQTCV_DET_COSTC-EXTWG .
ZQTC_DETRM_COSTC-WERKS =
ZQTCV_DET_COSTC-WERKS .
ZQTC_DETRM_COSTC-KOSTL =
ZQTCV_DET_COSTC-KOSTL .
ZQTC_DETRM_COSTC-AENAM =
ZQTCV_DET_COSTC-AENAM .
ZQTC_DETRM_COSTC-AEDAT =
ZQTCV_DET_COSTC-AEDAT .
ZQTC_DETRM_COSTC-AEZET =
ZQTCV_DET_COSTC-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_DETRM_COSTC .
    ELSE.
    INSERT ZQTC_DETRM_COSTC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_DET_COSTC-UPD_FLAG,
STATUS_ZQTCV_DET_COSTC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_DET_COSTC.
  SELECT SINGLE * FROM ZQTC_DETRM_COSTC WHERE
EXTWG = ZQTCV_DET_COSTC-EXTWG AND
WERKS = ZQTCV_DET_COSTC-WERKS .
ZQTCV_DET_COSTC-MANDT =
ZQTC_DETRM_COSTC-MANDT .
ZQTCV_DET_COSTC-EXTWG =
ZQTC_DETRM_COSTC-EXTWG .
ZQTCV_DET_COSTC-WERKS =
ZQTC_DETRM_COSTC-WERKS .
ZQTCV_DET_COSTC-KOSTL =
ZQTC_DETRM_COSTC-KOSTL .
ZQTCV_DET_COSTC-AENAM =
ZQTC_DETRM_COSTC-AENAM .
ZQTCV_DET_COSTC-AEDAT =
ZQTC_DETRM_COSTC-AEDAT .
ZQTCV_DET_COSTC-AEZET =
ZQTC_DETRM_COSTC-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_DET_COSTC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_DET_COSTC-EXTWG TO
ZQTC_DETRM_COSTC-EXTWG .
MOVE ZQTCV_DET_COSTC-WERKS TO
ZQTC_DETRM_COSTC-WERKS .
MOVE ZQTCV_DET_COSTC-MANDT TO
ZQTC_DETRM_COSTC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_DETRM_COSTC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_DETRM_COSTC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_DETRM_COSTC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
