*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_NOTIF_OUT.................................*
FORM GET_DATA_ZQTCV_NOTIF_OUT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_NOTIF_OUTPT WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_NOTIF_OUT .
ZQTCV_NOTIF_OUT-MANDT =
ZQTC_NOTIF_OUTPT-MANDT .
ZQTCV_NOTIF_OUT-NOTIF_PROF =
ZQTC_NOTIF_OUTPT-NOTIF_PROF .
ZQTCV_NOTIF_OUT-PROMO =
ZQTC_NOTIF_OUTPT-PROMO .
ZQTCV_NOTIF_OUT-COMM_METHOD =
ZQTC_NOTIF_OUTPT-COMM_METHOD .
ZQTCV_NOTIF_OUT-OUTPUT_TYPE =
ZQTC_NOTIF_OUTPT-OUTPUT_TYPE .
    SELECT SINGLE * FROM T685 WHERE
KVEWE = 'B' AND
KAPPL = 'V1' AND
KSCHL = ZQTC_NOTIF_OUTPT-OUTPUT_TYPE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T685T WHERE
KVEWE = T685-KVEWE AND
KAPPL = T685-KAPPL AND
KSCHL = T685-KSCHL AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_NOTIF_OUT-VTEXT =
T685T-VTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_NOTIF_OUT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_NOTIF_OUT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_NOTIF_OUT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_NOTIF_OUT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_NOTIF_OUTPT WHERE
  NOTIF_PROF = ZQTCV_NOTIF_OUT-NOTIF_PROF AND
  PROMO = ZQTCV_NOTIF_OUT-PROMO AND
  COMM_METHOD = ZQTCV_NOTIF_OUT-COMM_METHOD .
    IF SY-SUBRC = 0.
    DELETE ZQTC_NOTIF_OUTPT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_NOTIF_OUTPT WHERE
  NOTIF_PROF = ZQTCV_NOTIF_OUT-NOTIF_PROF AND
  PROMO = ZQTCV_NOTIF_OUT-PROMO AND
  COMM_METHOD = ZQTCV_NOTIF_OUT-COMM_METHOD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_NOTIF_OUTPT.
    ENDIF.
ZQTC_NOTIF_OUTPT-MANDT =
ZQTCV_NOTIF_OUT-MANDT .
ZQTC_NOTIF_OUTPT-NOTIF_PROF =
ZQTCV_NOTIF_OUT-NOTIF_PROF .
ZQTC_NOTIF_OUTPT-PROMO =
ZQTCV_NOTIF_OUT-PROMO .
ZQTC_NOTIF_OUTPT-COMM_METHOD =
ZQTCV_NOTIF_OUT-COMM_METHOD .
ZQTC_NOTIF_OUTPT-OUTPUT_TYPE =
ZQTCV_NOTIF_OUT-OUTPUT_TYPE .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_NOTIF_OUTPT .
    ELSE.
    INSERT ZQTC_NOTIF_OUTPT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_NOTIF_OUT-UPD_FLAG,
STATUS_ZQTCV_NOTIF_OUT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_NOTIF_OUT.
  SELECT SINGLE * FROM ZQTC_NOTIF_OUTPT WHERE
NOTIF_PROF = ZQTCV_NOTIF_OUT-NOTIF_PROF AND
PROMO = ZQTCV_NOTIF_OUT-PROMO AND
COMM_METHOD = ZQTCV_NOTIF_OUT-COMM_METHOD .
ZQTCV_NOTIF_OUT-MANDT =
ZQTC_NOTIF_OUTPT-MANDT .
ZQTCV_NOTIF_OUT-NOTIF_PROF =
ZQTC_NOTIF_OUTPT-NOTIF_PROF .
ZQTCV_NOTIF_OUT-PROMO =
ZQTC_NOTIF_OUTPT-PROMO .
ZQTCV_NOTIF_OUT-COMM_METHOD =
ZQTC_NOTIF_OUTPT-COMM_METHOD .
ZQTCV_NOTIF_OUT-OUTPUT_TYPE =
ZQTC_NOTIF_OUTPT-OUTPUT_TYPE .
    SELECT SINGLE * FROM T685 WHERE
KVEWE = 'B' AND
KAPPL = 'V1' AND
KSCHL = ZQTC_NOTIF_OUTPT-OUTPUT_TYPE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T685T WHERE
KVEWE = T685-KVEWE AND
KAPPL = T685-KAPPL AND
KSCHL = T685-KSCHL AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_NOTIF_OUT-VTEXT =
T685T-VTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_NOTIF_OUT-VTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_NOTIF_OUT-VTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_NOTIF_OUT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_NOTIF_OUT-NOTIF_PROF TO
ZQTC_NOTIF_OUTPT-NOTIF_PROF .
MOVE ZQTCV_NOTIF_OUT-PROMO TO
ZQTC_NOTIF_OUTPT-PROMO .
MOVE ZQTCV_NOTIF_OUT-COMM_METHOD TO
ZQTC_NOTIF_OUTPT-COMM_METHOD .
MOVE ZQTCV_NOTIF_OUT-MANDT TO
ZQTC_NOTIF_OUTPT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_NOTIF_OUTPT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_NOTIF_OUTPT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_NOTIF_OUTPT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZQTCV_NOTIF_OUT USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZQTC_NOTIF_OUTPT-MANDT =
ZQTCV_NOTIF_OUT-MANDT .
ZQTC_NOTIF_OUTPT-NOTIF_PROF =
ZQTCV_NOTIF_OUT-NOTIF_PROF .
ZQTC_NOTIF_OUTPT-PROMO =
ZQTCV_NOTIF_OUT-PROMO .
ZQTC_NOTIF_OUTPT-COMM_METHOD =
ZQTCV_NOTIF_OUT-COMM_METHOD .
ZQTC_NOTIF_OUTPT-OUTPUT_TYPE =
ZQTCV_NOTIF_OUT-OUTPUT_TYPE .
    SELECT SINGLE * FROM T685 WHERE
KVEWE = 'B' AND
KAPPL = 'V1' AND
KSCHL = ZQTC_NOTIF_OUTPT-OUTPUT_TYPE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T685T WHERE
KVEWE = T685-KVEWE AND
KAPPL = T685-KAPPL AND
KSCHL = T685-KSCHL AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_NOTIF_OUT-VTEXT =
T685T-VTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_NOTIF_OUT-VTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_NOTIF_OUT-VTEXT .
    ENDIF.
ENDFORM.
*...processing: ZQTCV_NOTIF_PDET................................*
FORM GET_DATA_ZQTCV_NOTIF_PDET.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_NOTIF_P_DET WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_NOTIF_PDET .
ZQTCV_NOTIF_PDET-MANDT =
ZQTC_NOTIF_P_DET-MANDT .
ZQTCV_NOTIF_PDET-NOTIF_PROF =
ZQTC_NOTIF_P_DET-NOTIF_PROF .
ZQTCV_NOTIF_PDET-NOTIF_REM =
ZQTC_NOTIF_P_DET-NOTIF_REM .
ZQTCV_NOTIF_PDET-REM_IN_DAYS =
ZQTC_NOTIF_P_DET-REM_IN_DAYS .
ZQTCV_NOTIF_PDET-PROMO_CODE =
ZQTC_NOTIF_P_DET-PROMO_CODE .
ZQTCV_NOTIF_PDET-AENAM =
ZQTC_NOTIF_P_DET-AENAM .
ZQTCV_NOTIF_PDET-AEDAT =
ZQTC_NOTIF_P_DET-AEDAT .
ZQTCV_NOTIF_PDET-AEZET =
ZQTC_NOTIF_P_DET-AEZET .
    SELECT SINGLE * FROM ZQTC_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_P_DET-NOTIF_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_NOTIF_PDET-NOTIF_PROF_D =
ZQTCT_NOTIF_PROF-NOTIF_PROF_D .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_NOTIF_PDET.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_NOTIF_PDET .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_NOTIF_PDET.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_NOTIF_PDET-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_NOTIF_P_DET WHERE
  NOTIF_PROF = ZQTCV_NOTIF_PDET-NOTIF_PROF AND
  NOTIF_REM = ZQTCV_NOTIF_PDET-NOTIF_REM .
    IF SY-SUBRC = 0.
    DELETE ZQTC_NOTIF_P_DET .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_NOTIF_P_DET WHERE
  NOTIF_PROF = ZQTCV_NOTIF_PDET-NOTIF_PROF AND
  NOTIF_REM = ZQTCV_NOTIF_PDET-NOTIF_REM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_NOTIF_P_DET.
    ENDIF.
ZQTC_NOTIF_P_DET-MANDT =
ZQTCV_NOTIF_PDET-MANDT .
ZQTC_NOTIF_P_DET-NOTIF_PROF =
ZQTCV_NOTIF_PDET-NOTIF_PROF .
ZQTC_NOTIF_P_DET-NOTIF_REM =
ZQTCV_NOTIF_PDET-NOTIF_REM .
ZQTC_NOTIF_P_DET-REM_IN_DAYS =
ZQTCV_NOTIF_PDET-REM_IN_DAYS .
ZQTC_NOTIF_P_DET-PROMO_CODE =
ZQTCV_NOTIF_PDET-PROMO_CODE .
ZQTC_NOTIF_P_DET-AENAM =
ZQTCV_NOTIF_PDET-AENAM .
ZQTC_NOTIF_P_DET-AEDAT =
ZQTCV_NOTIF_PDET-AEDAT .
ZQTC_NOTIF_P_DET-AEZET =
ZQTCV_NOTIF_PDET-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_NOTIF_P_DET .
    ELSE.
    INSERT ZQTC_NOTIF_P_DET .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_NOTIF_PDET-UPD_FLAG,
STATUS_ZQTCV_NOTIF_PDET-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_NOTIF_PDET.
  SELECT SINGLE * FROM ZQTC_NOTIF_P_DET WHERE
NOTIF_PROF = ZQTCV_NOTIF_PDET-NOTIF_PROF AND
NOTIF_REM = ZQTCV_NOTIF_PDET-NOTIF_REM .
ZQTCV_NOTIF_PDET-MANDT =
ZQTC_NOTIF_P_DET-MANDT .
ZQTCV_NOTIF_PDET-NOTIF_PROF =
ZQTC_NOTIF_P_DET-NOTIF_PROF .
ZQTCV_NOTIF_PDET-NOTIF_REM =
ZQTC_NOTIF_P_DET-NOTIF_REM .
ZQTCV_NOTIF_PDET-REM_IN_DAYS =
ZQTC_NOTIF_P_DET-REM_IN_DAYS .
ZQTCV_NOTIF_PDET-PROMO_CODE =
ZQTC_NOTIF_P_DET-PROMO_CODE .
ZQTCV_NOTIF_PDET-AENAM =
ZQTC_NOTIF_P_DET-AENAM .
ZQTCV_NOTIF_PDET-AEDAT =
ZQTC_NOTIF_P_DET-AEDAT .
ZQTCV_NOTIF_PDET-AEZET =
ZQTC_NOTIF_P_DET-AEZET .
    SELECT SINGLE * FROM ZQTC_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_P_DET-NOTIF_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_NOTIF_PDET-NOTIF_PROF_D =
ZQTCT_NOTIF_PROF-NOTIF_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_NOTIF_PDET-NOTIF_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_NOTIF_PDET-NOTIF_PROF_D .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_NOTIF_PDET USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_NOTIF_PDET-NOTIF_PROF TO
ZQTC_NOTIF_P_DET-NOTIF_PROF .
MOVE ZQTCV_NOTIF_PDET-NOTIF_REM TO
ZQTC_NOTIF_P_DET-NOTIF_REM .
MOVE ZQTCV_NOTIF_PDET-MANDT TO
ZQTC_NOTIF_P_DET-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_NOTIF_P_DET'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_NOTIF_P_DET TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_NOTIF_P_DET'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZQTCV_NOTIF_PDET USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZQTC_NOTIF_P_DET-MANDT =
ZQTCV_NOTIF_PDET-MANDT .
ZQTC_NOTIF_P_DET-NOTIF_PROF =
ZQTCV_NOTIF_PDET-NOTIF_PROF .
ZQTC_NOTIF_P_DET-NOTIF_REM =
ZQTCV_NOTIF_PDET-NOTIF_REM .
ZQTC_NOTIF_P_DET-REM_IN_DAYS =
ZQTCV_NOTIF_PDET-REM_IN_DAYS .
ZQTC_NOTIF_P_DET-PROMO_CODE =
ZQTCV_NOTIF_PDET-PROMO_CODE .
ZQTC_NOTIF_P_DET-AENAM =
ZQTCV_NOTIF_PDET-AENAM .
ZQTC_NOTIF_P_DET-AEDAT =
ZQTCV_NOTIF_PDET-AEDAT .
ZQTC_NOTIF_P_DET-AEZET =
ZQTCV_NOTIF_PDET-AEZET .
    SELECT SINGLE * FROM ZQTC_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_P_DET-NOTIF_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_NOTIF_PDET-NOTIF_PROF_D =
ZQTCT_NOTIF_PROF-NOTIF_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_NOTIF_PDET-NOTIF_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_NOTIF_PDET-NOTIF_PROF_D .
    ENDIF.
ENDFORM.
*...processing: ZQTCV_NOTIF_PROF................................*
FORM GET_DATA_ZQTCV_NOTIF_PROF.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_NOTIF_PROF WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_NOTIF_PROF .
ZQTCV_NOTIF_PROF-MANDT =
ZQTC_NOTIF_PROF-MANDT .
ZQTCV_NOTIF_PROF-NOTIF_PROF =
ZQTC_NOTIF_PROF-NOTIF_PROF .
ZQTCV_NOTIF_PROF-AENAM =
ZQTC_NOTIF_PROF-AENAM .
ZQTCV_NOTIF_PROF-AEDAT =
ZQTC_NOTIF_PROF-AEDAT .
ZQTCV_NOTIF_PROF-AEZET =
ZQTC_NOTIF_PROF-AEZET .
    SELECT SINGLE * FROM ZQTCT_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZQTCV_NOTIF_PROF-NOTIF_PROF_D =
ZQTCT_NOTIF_PROF-NOTIF_PROF_D .
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_NOTIF_PROF.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_NOTIF_PROF .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_NOTIF_PROF.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_NOTIF_PROF-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_NOTIF_PROF WHERE
  NOTIF_PROF = ZQTCV_NOTIF_PROF-NOTIF_PROF .
    IF SY-SUBRC = 0.
    DELETE ZQTC_NOTIF_PROF .
    ENDIF.
    DELETE FROM ZQTCT_NOTIF_PROF WHERE
    NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_NOTIF_PROF WHERE
  NOTIF_PROF = ZQTCV_NOTIF_PROF-NOTIF_PROF .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_NOTIF_PROF.
    ENDIF.
ZQTC_NOTIF_PROF-MANDT =
ZQTCV_NOTIF_PROF-MANDT .
ZQTC_NOTIF_PROF-NOTIF_PROF =
ZQTCV_NOTIF_PROF-NOTIF_PROF .
ZQTC_NOTIF_PROF-AENAM =
ZQTCV_NOTIF_PROF-AENAM .
ZQTC_NOTIF_PROF-AEDAT =
ZQTCV_NOTIF_PROF-AEDAT .
ZQTC_NOTIF_PROF-AEZET =
ZQTCV_NOTIF_PROF-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_NOTIF_PROF .
    ELSE.
    INSERT ZQTC_NOTIF_PROF .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZQTCT_NOTIF_PROF WHERE
    NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZQTCT_NOTIF_PROF.
ZQTCT_NOTIF_PROF-NOTIF_PROF =
ZQTC_NOTIF_PROF-NOTIF_PROF .
ZQTCT_NOTIF_PROF-SPRAS =
SY-LANGU .
      ENDIF.
ZQTCT_NOTIF_PROF-NOTIF_PROF_D =
ZQTCV_NOTIF_PROF-NOTIF_PROF_D .
    IF SY-SUBRC = 0.
    UPDATE ZQTCT_NOTIF_PROF .
    ELSE.
    INSERT ZQTCT_NOTIF_PROF .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_NOTIF_PROF-UPD_FLAG,
STATUS_ZQTCV_NOTIF_PROF-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_NOTIF_PROF.
  SELECT SINGLE * FROM ZQTC_NOTIF_PROF WHERE
NOTIF_PROF = ZQTCV_NOTIF_PROF-NOTIF_PROF .
ZQTCV_NOTIF_PROF-MANDT =
ZQTC_NOTIF_PROF-MANDT .
ZQTCV_NOTIF_PROF-NOTIF_PROF =
ZQTC_NOTIF_PROF-NOTIF_PROF .
ZQTCV_NOTIF_PROF-AENAM =
ZQTC_NOTIF_PROF-AENAM .
ZQTCV_NOTIF_PROF-AEDAT =
ZQTC_NOTIF_PROF-AEDAT .
ZQTCV_NOTIF_PROF-AEZET =
ZQTC_NOTIF_PROF-AEZET .
    SELECT SINGLE * FROM ZQTCT_NOTIF_PROF WHERE
NOTIF_PROF = ZQTC_NOTIF_PROF-NOTIF_PROF AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZQTCV_NOTIF_PROF-NOTIF_PROF_D =
ZQTCT_NOTIF_PROF-NOTIF_PROF_D .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_NOTIF_PROF-NOTIF_PROF_D .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_NOTIF_PROF USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_NOTIF_PROF-NOTIF_PROF TO
ZQTC_NOTIF_PROF-NOTIF_PROF .
MOVE ZQTCV_NOTIF_PROF-MANDT TO
ZQTC_NOTIF_PROF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_NOTIF_PROF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_NOTIF_PROF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_NOTIF_PROF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZQTC_NOTIF_PROF-NOTIF_PROF TO
ZQTCT_NOTIF_PROF-NOTIF_PROF .
MOVE SY-LANGU TO
ZQTCT_NOTIF_PROF-SPRAS .
MOVE ZQTCV_NOTIF_PROF-MANDT TO
ZQTCT_NOTIF_PROF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTCT_NOTIF_PROF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTCT_NOTIF_PROF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTCT_NOTIF_PROF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
