*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_RP_DETER..................................*
FORM GET_DATA_ZQTCV_RP_DETER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_RP_DETER WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_RP_DETER .
ZQTCV_RP_DETER-MANDT =
ZQTC_RP_DETER-MANDT .
ZQTCV_RP_DETER-KDGRP =
ZQTC_RP_DETER-KDGRP .
ZQTCV_RP_DETER-KONDA =
ZQTC_RP_DETER-KONDA .
ZQTCV_RP_DETER-PAY_TYPE =
ZQTC_RP_DETER-PAY_TYPE .
ZQTCV_RP_DETER-SOLD_TO_COUNTRY =
ZQTC_RP_DETER-SOLD_TO_COUNTRY .
ZQTCV_RP_DETER-SHIP_TO_COUNTRY =
ZQTC_RP_DETER-SHIP_TO_COUNTRY .
ZQTCV_RP_DETER-LICENSE_GRP =
ZQTC_RP_DETER-LICENSE_GRP .
ZQTCV_RP_DETER-SALES_OFFICE =
ZQTC_RP_DETER-SALES_OFFICE .
ZQTCV_RP_DETER-SUBS_TYPE =
ZQTC_RP_DETER-SUBS_TYPE .
ZQTCV_RP_DETER-KDKG2 =
ZQTC_RP_DETER-KDKG2 .
ZQTCV_RP_DETER-MVGR5 =
ZQTC_RP_DETER-MVGR5 .
ZQTCV_RP_DETER-BSARK =
ZQTC_RP_DETER-BSARK .
ZQTCV_RP_DETER-VKORG =
ZQTC_RP_DETER-VKORG .
ZQTCV_RP_DETER-WERKS =
ZQTC_RP_DETER-WERKS .
ZQTCV_RP_DETER-MATNR =
ZQTC_RP_DETER-MATNR .
ZQTCV_RP_DETER-ZZACTION =
ZQTC_RP_DETER-ZZACTION .
ZQTCV_RP_DETER-RENWL_PROF =
ZQTC_RP_DETER-RENWL_PROF .
ZQTCV_RP_DETER-AENAM =
ZQTC_RP_DETER-AENAM .
ZQTCV_RP_DETER-AEDAT =
ZQTC_RP_DETER-AEDAT .
ZQTCV_RP_DETER-AEZET =
ZQTC_RP_DETER-AEZET .
    SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RP_DETER-RENWL_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RP_DETER-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_RP_DETER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_RP_DETER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_RP_DETER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_RP_DETER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RP_DETER WHERE
  KDGRP = ZQTCV_RP_DETER-KDGRP AND
  KONDA = ZQTCV_RP_DETER-KONDA AND
  PAY_TYPE = ZQTCV_RP_DETER-PAY_TYPE AND
  SOLD_TO_COUNTRY = ZQTCV_RP_DETER-SOLD_TO_COUNTRY AND
  SHIP_TO_COUNTRY = ZQTCV_RP_DETER-SHIP_TO_COUNTRY AND
  LICENSE_GRP = ZQTCV_RP_DETER-LICENSE_GRP AND
  SALES_OFFICE = ZQTCV_RP_DETER-SALES_OFFICE AND
  SUBS_TYPE = ZQTCV_RP_DETER-SUBS_TYPE AND
  KDKG2 = ZQTCV_RP_DETER-KDKG2 AND
  MVGR5 = ZQTCV_RP_DETER-MVGR5 AND
  BSARK = ZQTCV_RP_DETER-BSARK AND
  VKORG = ZQTCV_RP_DETER-VKORG AND
  WERKS = ZQTCV_RP_DETER-WERKS AND
  MATNR = ZQTCV_RP_DETER-MATNR AND
  ZZACTION = ZQTCV_RP_DETER-ZZACTION .
    IF SY-SUBRC = 0.
    DELETE ZQTC_RP_DETER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RP_DETER WHERE
  KDGRP = ZQTCV_RP_DETER-KDGRP AND
  KONDA = ZQTCV_RP_DETER-KONDA AND
  PAY_TYPE = ZQTCV_RP_DETER-PAY_TYPE AND
  SOLD_TO_COUNTRY = ZQTCV_RP_DETER-SOLD_TO_COUNTRY AND
  SHIP_TO_COUNTRY = ZQTCV_RP_DETER-SHIP_TO_COUNTRY AND
  LICENSE_GRP = ZQTCV_RP_DETER-LICENSE_GRP AND
  SALES_OFFICE = ZQTCV_RP_DETER-SALES_OFFICE AND
  SUBS_TYPE = ZQTCV_RP_DETER-SUBS_TYPE AND
  KDKG2 = ZQTCV_RP_DETER-KDKG2 AND
  MVGR5 = ZQTCV_RP_DETER-MVGR5 AND
  BSARK = ZQTCV_RP_DETER-BSARK AND
  VKORG = ZQTCV_RP_DETER-VKORG AND
  WERKS = ZQTCV_RP_DETER-WERKS AND
  MATNR = ZQTCV_RP_DETER-MATNR AND
  ZZACTION = ZQTCV_RP_DETER-ZZACTION .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_RP_DETER.
    ENDIF.
ZQTC_RP_DETER-MANDT =
ZQTCV_RP_DETER-MANDT .
ZQTC_RP_DETER-KDGRP =
ZQTCV_RP_DETER-KDGRP .
ZQTC_RP_DETER-KONDA =
ZQTCV_RP_DETER-KONDA .
ZQTC_RP_DETER-PAY_TYPE =
ZQTCV_RP_DETER-PAY_TYPE .
ZQTC_RP_DETER-SOLD_TO_COUNTRY =
ZQTCV_RP_DETER-SOLD_TO_COUNTRY .
ZQTC_RP_DETER-SHIP_TO_COUNTRY =
ZQTCV_RP_DETER-SHIP_TO_COUNTRY .
ZQTC_RP_DETER-LICENSE_GRP =
ZQTCV_RP_DETER-LICENSE_GRP .
ZQTC_RP_DETER-SALES_OFFICE =
ZQTCV_RP_DETER-SALES_OFFICE .
ZQTC_RP_DETER-SUBS_TYPE =
ZQTCV_RP_DETER-SUBS_TYPE .
ZQTC_RP_DETER-KDKG2 =
ZQTCV_RP_DETER-KDKG2 .
ZQTC_RP_DETER-MVGR5 =
ZQTCV_RP_DETER-MVGR5 .
ZQTC_RP_DETER-BSARK =
ZQTCV_RP_DETER-BSARK .
ZQTC_RP_DETER-VKORG =
ZQTCV_RP_DETER-VKORG .
ZQTC_RP_DETER-WERKS =
ZQTCV_RP_DETER-WERKS .
ZQTC_RP_DETER-MATNR =
ZQTCV_RP_DETER-MATNR .
ZQTC_RP_DETER-ZZACTION =
ZQTCV_RP_DETER-ZZACTION .
ZQTC_RP_DETER-RENWL_PROF =
ZQTCV_RP_DETER-RENWL_PROF .
ZQTC_RP_DETER-AENAM =
ZQTCV_RP_DETER-AENAM .
ZQTC_RP_DETER-AEDAT =
ZQTCV_RP_DETER-AEDAT .
ZQTC_RP_DETER-AEZET =
ZQTCV_RP_DETER-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_RP_DETER .
    ELSE.
    INSERT ZQTC_RP_DETER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_RP_DETER-UPD_FLAG,
STATUS_ZQTCV_RP_DETER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_RP_DETER.
  SELECT SINGLE * FROM ZQTC_RP_DETER WHERE
KDGRP = ZQTCV_RP_DETER-KDGRP AND
KONDA = ZQTCV_RP_DETER-KONDA AND
PAY_TYPE = ZQTCV_RP_DETER-PAY_TYPE AND
SOLD_TO_COUNTRY = ZQTCV_RP_DETER-SOLD_TO_COUNTRY AND
SHIP_TO_COUNTRY = ZQTCV_RP_DETER-SHIP_TO_COUNTRY AND
LICENSE_GRP = ZQTCV_RP_DETER-LICENSE_GRP AND
SALES_OFFICE = ZQTCV_RP_DETER-SALES_OFFICE AND
SUBS_TYPE = ZQTCV_RP_DETER-SUBS_TYPE AND
KDKG2 = ZQTCV_RP_DETER-KDKG2 AND
MVGR5 = ZQTCV_RP_DETER-MVGR5 AND
BSARK = ZQTCV_RP_DETER-BSARK AND
VKORG = ZQTCV_RP_DETER-VKORG AND
WERKS = ZQTCV_RP_DETER-WERKS AND
MATNR = ZQTCV_RP_DETER-MATNR AND
ZZACTION = ZQTCV_RP_DETER-ZZACTION .
ZQTCV_RP_DETER-MANDT =
ZQTC_RP_DETER-MANDT .
ZQTCV_RP_DETER-KDGRP =
ZQTC_RP_DETER-KDGRP .
ZQTCV_RP_DETER-KONDA =
ZQTC_RP_DETER-KONDA .
ZQTCV_RP_DETER-PAY_TYPE =
ZQTC_RP_DETER-PAY_TYPE .
ZQTCV_RP_DETER-SOLD_TO_COUNTRY =
ZQTC_RP_DETER-SOLD_TO_COUNTRY .
ZQTCV_RP_DETER-SHIP_TO_COUNTRY =
ZQTC_RP_DETER-SHIP_TO_COUNTRY .
ZQTCV_RP_DETER-LICENSE_GRP =
ZQTC_RP_DETER-LICENSE_GRP .
ZQTCV_RP_DETER-SALES_OFFICE =
ZQTC_RP_DETER-SALES_OFFICE .
ZQTCV_RP_DETER-SUBS_TYPE =
ZQTC_RP_DETER-SUBS_TYPE .
ZQTCV_RP_DETER-KDKG2 =
ZQTC_RP_DETER-KDKG2 .
ZQTCV_RP_DETER-MVGR5 =
ZQTC_RP_DETER-MVGR5 .
ZQTCV_RP_DETER-BSARK =
ZQTC_RP_DETER-BSARK .
ZQTCV_RP_DETER-VKORG =
ZQTC_RP_DETER-VKORG .
ZQTCV_RP_DETER-WERKS =
ZQTC_RP_DETER-WERKS .
ZQTCV_RP_DETER-MATNR =
ZQTC_RP_DETER-MATNR .
ZQTCV_RP_DETER-ZZACTION =
ZQTC_RP_DETER-ZZACTION .
ZQTCV_RP_DETER-RENWL_PROF =
ZQTC_RP_DETER-RENWL_PROF .
ZQTCV_RP_DETER-AENAM =
ZQTC_RP_DETER-AENAM .
ZQTCV_RP_DETER-AEDAT =
ZQTC_RP_DETER-AEDAT .
ZQTCV_RP_DETER-AEZET =
ZQTC_RP_DETER-AEZET .
    SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RP_DETER-RENWL_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RP_DETER-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RP_DETER-RENWL_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RP_DETER-RENWL_PROF_D .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_RP_DETER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_RP_DETER-KDGRP TO
ZQTC_RP_DETER-KDGRP .
MOVE ZQTCV_RP_DETER-KONDA TO
ZQTC_RP_DETER-KONDA .
MOVE ZQTCV_RP_DETER-PAY_TYPE TO
ZQTC_RP_DETER-PAY_TYPE .
MOVE ZQTCV_RP_DETER-SOLD_TO_COUNTRY TO
ZQTC_RP_DETER-SOLD_TO_COUNTRY .
MOVE ZQTCV_RP_DETER-SHIP_TO_COUNTRY TO
ZQTC_RP_DETER-SHIP_TO_COUNTRY .
MOVE ZQTCV_RP_DETER-LICENSE_GRP TO
ZQTC_RP_DETER-LICENSE_GRP .
MOVE ZQTCV_RP_DETER-SALES_OFFICE TO
ZQTC_RP_DETER-SALES_OFFICE .
MOVE ZQTCV_RP_DETER-SUBS_TYPE TO
ZQTC_RP_DETER-SUBS_TYPE .
MOVE ZQTCV_RP_DETER-KDKG2 TO
ZQTC_RP_DETER-KDKG2 .
MOVE ZQTCV_RP_DETER-MVGR5 TO
ZQTC_RP_DETER-MVGR5 .
MOVE ZQTCV_RP_DETER-BSARK TO
ZQTC_RP_DETER-BSARK .
MOVE ZQTCV_RP_DETER-VKORG TO
ZQTC_RP_DETER-VKORG .
MOVE ZQTCV_RP_DETER-WERKS TO
ZQTC_RP_DETER-WERKS .
MOVE ZQTCV_RP_DETER-MATNR TO
ZQTC_RP_DETER-MATNR .
MOVE ZQTCV_RP_DETER-ZZACTION TO
ZQTC_RP_DETER-ZZACTION .
MOVE ZQTCV_RP_DETER-MANDT TO
ZQTC_RP_DETER-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_RP_DETER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_RP_DETER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_RP_DETER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZQTCV_RP_DETER USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZQTC_RP_DETER-MANDT =
ZQTCV_RP_DETER-MANDT .
ZQTC_RP_DETER-KDGRP =
ZQTCV_RP_DETER-KDGRP .
ZQTC_RP_DETER-KONDA =
ZQTCV_RP_DETER-KONDA .
ZQTC_RP_DETER-PAY_TYPE =
ZQTCV_RP_DETER-PAY_TYPE .
ZQTC_RP_DETER-SOLD_TO_COUNTRY =
ZQTCV_RP_DETER-SOLD_TO_COUNTRY .
ZQTC_RP_DETER-SHIP_TO_COUNTRY =
ZQTCV_RP_DETER-SHIP_TO_COUNTRY .
ZQTC_RP_DETER-LICENSE_GRP =
ZQTCV_RP_DETER-LICENSE_GRP .
ZQTC_RP_DETER-SALES_OFFICE =
ZQTCV_RP_DETER-SALES_OFFICE .
ZQTC_RP_DETER-SUBS_TYPE =
ZQTCV_RP_DETER-SUBS_TYPE .
ZQTC_RP_DETER-KDKG2 =
ZQTCV_RP_DETER-KDKG2 .
ZQTC_RP_DETER-MVGR5 =
ZQTCV_RP_DETER-MVGR5 .
ZQTC_RP_DETER-BSARK =
ZQTCV_RP_DETER-BSARK .
ZQTC_RP_DETER-VKORG =
ZQTCV_RP_DETER-VKORG .
ZQTC_RP_DETER-WERKS =
ZQTCV_RP_DETER-WERKS .
ZQTC_RP_DETER-MATNR =
ZQTCV_RP_DETER-MATNR .
ZQTC_RP_DETER-ZZACTION =
ZQTCV_RP_DETER-ZZACTION .
ZQTC_RP_DETER-RENWL_PROF =
ZQTCV_RP_DETER-RENWL_PROF .
ZQTC_RP_DETER-AENAM =
ZQTCV_RP_DETER-AENAM .
ZQTC_RP_DETER-AEDAT =
ZQTCV_RP_DETER-AEDAT .
ZQTC_RP_DETER-AEZET =
ZQTCV_RP_DETER-AEZET .
    SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RP_DETER-RENWL_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RP_DETER-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RP_DETER-RENWL_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RP_DETER-RENWL_PROF_D .
    ENDIF.
ENDFORM.
