FUNCTION-POOL zqtc_fg_order_inbound_if.     "MESSAGE-ID ..

* INCLUDE LZQTC_FG_ORDER_INBOUND_IFD...      " Local class definition

TYPES : BEGIN OF ty_header,
          crcy     TYPE edi6345_a,
          zterm TYPE DZTERM,
          lifsk TYPE lifsk,
          submi TYPE submi,
          doctype  TYPE auart,
          sorg     TYPE vkorg,
          dch      TYPE vtweg,
          division TYPE spart,
          saleoff  TYPE vkbur,
          potype   TYPE BSARK,
          date     TYPE edidat8,
          po       TYPE edi_belnr,
          name     TYPE BNAME_V,
          REF_1_S  TYPE IHREZ_E,
          cardtype TYPE ccins,
          cardnum  TYPE ccnum,
          cardname TYPE ccname,
          expdate  TYPE edidat8,
        END OF ty_header,

        BEGIN OF ty_partner,
          partner TYPE kunnr,
          item    TYPE posnr,
          pf      TYPE parvw,
        END OF ty_partner,

        BEGIN OF ty_text,
          item   TYPE posnr,
          tdid   TYPE edi4451_a,
          spras  TYPE edi3453_a,
          text   TYPE edi4040_a,
          format TYPE tdformat,
        END OF ty_text,

        BEGIN OF ty_item,
          item              TYPE posex,
          menge             TYPE edi_menge,
          pstyv             TYPE pstyv,
          belnr             TYPE edi_belnr,
        END OF ty_item,

        BEGIN OF ty_mat,
         item TYPE posex,
         matnr TYPE matnr,
         kdmat TYPE kdmat,
        END OF ty_mat,

        BEGIN OF ty_poitem,
        item TYPE posex,
        zeile TYPE edi1082_a,
        END OF ty_poitem,

        BEGIN OF ty_item_date,
        item TYPE posex,
        date TYPE edidat8,
        END OF ty_item_date,

        BEGIN OF ty_item_add,
        item TYPE posex,
        PRC_GROUP1 TYPE MVGR1,
        CSTCNDGRP5 TYPE KDKG5,
        CUSADD TYPE char35,
        END OF ty_item_add,

        BEGIN OF ty_item_cust,
          vposn             TYPE posnr_va,
          vbegdat           TYPE vbdat_veda,
          venddat           TYPE vndat_veda,
          zzcontent_start_d TYPE  dats,
          zzcontent_end_d   TYPE dats,
          zzlicense_start_d TYPE  dats,
          zzlicense_end_d   TYPE  dats,
        END OF ty_item_cust,
        BEGIN OF ty_cond,
          item  TYPE posnr,
          kschl TYPE kschl,
          betrg TYPE edi5004_p,
        END OF ty_cond.

DATA : gst_header  TYPE ty_header,
       gi_partner TYPE STANDARD TABLE OF ty_partner,
       gst_partner TYPE ty_partner,
       gi_text    TYPE STANDARD TABLE OF ty_text,
       gst_text    TYPE ty_text,
       gi_item    TYPE STANDARD TABLE OF ty_item,
       gst_item    TYPE ty_item,
       gi_cond    TYPE STANDARD TABLE OF ty_cond,
       gst_cond    TYPE ty_cond,
       gi_mat TYPE STANDARD TABLE OF ty_mat,
       gst_mat TYPE ty_mat,
       gi_item_cust TYPE STANDARD TABLE OF ty_item_cust,
       gst_item_cust TYPE ty_item_cust,
       gi_poitem TYPE STANDARD TABLE OF ty_poitem,
       gst_poitem TYPE ty_poitem,
       gi_item_date TYPE STANDARD TABLE OF ty_item_date,
       gst_item_date TYPE ty_item_date,
       gi_item_add TYPE STANDARD TABLE OF ty_item_add,
       gst_item_add TYPE ty_item_add,
       gi_return    TYPE STANDARD TABLE OF bapiret2,
       gi_bapi_items      TYPE STANDARD TABLE OF BAPISDITM,
       gi_bapi_itemsx     TYPE STANDARD TABLE OF BAPISDITMX,
       gi_bapi_partners  TYPE STANDARD TABLE OF BAPIPARNR,
       gi_bapi_cond      TYPE STANDARD TABLE OF BAPICOND,
       gi_bapi_condx TYPE STANDARD TABLE OF BAPICONDX,
       gi_bapi_card      TYPE STANDARD TABLE OF BAPICCARD,
       gi_bapi_text TYPE STANDARD TABLE OF BAPISDTEXT,
       gi_bapi_ext TYPE STANDARD TABLE OF BAPIPAREX,
       gi_bapi_contract TYPE STANDARD TABLE OF BAPICTR,
       gi_bapi_contractx TYPE STANDARD TABLE OF BAPICTRX,
       gst_bapi_header   TYPE BAPISDHD1,
       gst_bapi_headerx  TYPE BAPISDHD1X,
       gv_doc       TYPE bapivbeln-vbeln,
       gv_idoc TYPE EDI_DOCNUM,
       gst_return   TYPE bapiret2,
       gst_bapi_items     TYPE BAPISDITM,
       gst_bapi_itemsx    TYPE BAPISDITMX,
       gst_bapi_partners TYPE BAPIPARNR,
       gst_bapi_cond     TYPE BAPICOND,
       gst_bapi_condx TYPE BAPICONDX,
       gst_bapi_card     TYPE BAPICCARD,
       gst_bapi_text TYPE BAPISDTEXT,
       gst_bapi_contract TYPE BAPICTR,
       gst_bapi_contractx TYPE BAPICTRX,
       gst_bapi_ext TYPE BAPIPAREX.

CONSTANTS :
    c_error            TYPE symsgty VALUE 'E',     " Error
    c_e1edk01          TYPE char7 VALUE 'E1EDK01',
    c_e1edk36          TYPE char7 VALUE 'E1EDK36', " E1EDK36
    c_e1edk14          TYPE char7 VALUE 'E1EDK14', " E1EDK14
    c_e1edk02          TYPE char7 VALUE 'E1EDK02', " E1EDK02
    c_e1edka1          TYPE char7 VALUE 'E1EDKA1',   " E1EDKA1 segment
    c_e1edka3          TYPE char7 VALUE 'E1EDKA3',   " E1EDKA1 segment
    c_e1edkt1          TYPE char7 VALUE 'E1EDKT1',
    c_e1edkt2          TYPE char7 VALUE 'E1EDKT2',
    c_e1edp01          TYPE char7 VALUE 'E1EDP01',
    c_e1edp02          TYPE char7 VALUE 'E1EDP02',
    c_e1edp03          TYPE char7 VALUE 'E1EDP03',
    c_e1edp04          TYPE char7 VALUE 'E1EDP04',
    c_e1edp05          TYPE char7 VALUE 'E1EDP05',
    c_e1edpa1          TYPE char7 VALUE 'E1EDPA1',
    c_e1edp19          TYPE char7 VALUE 'E1EDP19',
    c_e1edp35          TYPE char7 VALUE 'E1EDP35',
    c_e1edpt1          TYPE char7 VALUE 'E1EDPT1',
    c_e1edpt2          TYPE char7 VALUE 'E1EDPT2',
    c_e1edk03 TYPE char7 VALUE 'E1EDk03',
    c_z1qtc_e1edk01    TYPE char20 VALUE 'Z1QTC_E1EDK01_01',
    c_z1qtc_e1edp01_01 TYPE char20 VALUE 'Z1QTC_E1EDP01_01',
    c_bus2034 TYPE BAPIUSW01-OBJTYPE VALUE 'BUS2034',
    c_parvw_re         TYPE parvw VALUE 'RE',        " Bill to Party
    c_parvw_rg         TYPE parvw VALUE 'RG',        " Payer
    c_parvw_we         TYPE parvw VALUE 'WE',        " Ship to Party
    c_parvw_ag         TYPE parvw VALUE 'AG',        " Sold to Party
    c_qualf_012       TYPE char3 VALUE '012',
    c_qualf_008       TYPE char3 VALUE '008',
    c_qualf_006       TYPE char3 VALUE '006',
    c_qualf_007       TYPE char3 VALUE '007',
    c_qualf_016       TYPE char3 VALUE '016',
    c_qualf_019       TYPE char3 VALUE '019',
    c_qualf_022       TYPE char3 VALUE '022',
    c_qualf_44         TYPE char3 VALUE '44',
    c_qualf_001        TYPE char3 VALUE '001',
    c_qalf_002         TYPE char3 VALUE '002',
    c_qalf_001 TYPE char3 VALUE '001',
    c_qualf_005        TYPE char3 VALUE '005',
    c_qualf_010        TYPE char3 VALUE '010',
    c_pf_ag TYPE char2 VALUE 'AG',
    c_pf_we TYPE char2 VALUE 'WE',
    c_zmbr TYPE char4 VALUE 'ZMBR',
    c_status_53 TYPE char2 VALUE '53',
    c_status_51 TYPE char2 value '51',
    c_header_item TYPE char6 VALUE '000000',
    c_x TYPE c VALUE 'X',
    c_e TYPE c VALUE 'E',
    c_a TYPE c VALUE 'A',
    c_s TYPE c VALUE 'S' .
