*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_I0255_SPLT................................*
FORM GET_DATA_ZQTCV_I0255_SPLT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_I0255_SPLIT WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_I0255_SPLT .
ZQTCV_I0255_SPLT-MANDT =
ZQTC_I0255_SPLIT-MANDT .
ZQTCV_I0255_SPLT-LABLTP =
ZQTC_I0255_SPLIT-LABLTP .
ZQTCV_I0255_SPLT-VARNAME =
ZQTC_I0255_SPLIT-VARNAME .
ZQTCV_I0255_SPLT-ZSEQNO =
ZQTC_I0255_SPLIT-ZSEQNO .
ZQTCV_I0255_SPLT-MEDIA_PRODUCT =
ZQTC_I0255_SPLIT-MEDIA_PRODUCT .
ZQTCV_I0255_SPLT-MEDIA_ISSUE =
ZQTC_I0255_SPLIT-MEDIA_ISSUE .
ZQTCV_I0255_SPLT-PRICE_GRP =
ZQTC_I0255_SPLIT-PRICE_GRP .
ZQTCV_I0255_SPLT-SHIP_TO_CODE =
ZQTC_I0255_SPLIT-SHIP_TO_CODE .
ZQTCV_I0255_SPLT-SOCIETY_GRP_CODE =
ZQTC_I0255_SPLIT-SOCIETY_GRP_CODE .
ZQTCV_I0255_SPLT-REASON_CODE =
ZQTC_I0255_SPLIT-REASON_CODE .
ZQTCV_I0255_SPLT-SUBSCRIPTION_CLS =
ZQTC_I0255_SPLIT-SUBSCRIPTION_CLS .
ZQTCV_I0255_SPLT-SALES_ORG =
ZQTC_I0255_SPLIT-SALES_ORG .
ZQTCV_I0255_SPLT-CONDITION_GRP2 =
ZQTC_I0255_SPLIT-CONDITION_GRP2 .
ZQTCV_I0255_SPLT-CNTRL_CIRCULATION =
ZQTC_I0255_SPLIT-CNTRL_CIRCULATION .
ZQTCV_I0255_SPLT-VARSPLIT =
ZQTC_I0255_SPLIT-VARSPLIT .
ZQTCV_I0255_SPLT-EMAIL =
ZQTC_I0255_SPLIT-EMAIL .
<VIM_TOTAL_STRUC> = ZQTCV_I0255_SPLT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_I0255_SPLT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_I0255_SPLT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_I0255_SPLT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_I0255_SPLIT WHERE
  LABLTP = ZQTCV_I0255_SPLT-LABLTP AND
  VARNAME = ZQTCV_I0255_SPLT-VARNAME AND
  ZSEQNO = ZQTCV_I0255_SPLT-ZSEQNO AND
  MEDIA_PRODUCT = ZQTCV_I0255_SPLT-MEDIA_PRODUCT .
    IF SY-SUBRC = 0.
    DELETE ZQTC_I0255_SPLIT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_I0255_SPLIT WHERE
  LABLTP = ZQTCV_I0255_SPLT-LABLTP AND
  VARNAME = ZQTCV_I0255_SPLT-VARNAME AND
  ZSEQNO = ZQTCV_I0255_SPLT-ZSEQNO AND
  MEDIA_PRODUCT = ZQTCV_I0255_SPLT-MEDIA_PRODUCT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_I0255_SPLIT.
    ENDIF.
ZQTC_I0255_SPLIT-MANDT =
ZQTCV_I0255_SPLT-MANDT .
ZQTC_I0255_SPLIT-LABLTP =
ZQTCV_I0255_SPLT-LABLTP .
ZQTC_I0255_SPLIT-VARNAME =
ZQTCV_I0255_SPLT-VARNAME .
ZQTC_I0255_SPLIT-ZSEQNO =
ZQTCV_I0255_SPLT-ZSEQNO .
ZQTC_I0255_SPLIT-MEDIA_PRODUCT =
ZQTCV_I0255_SPLT-MEDIA_PRODUCT .
ZQTC_I0255_SPLIT-MEDIA_ISSUE =
ZQTCV_I0255_SPLT-MEDIA_ISSUE .
ZQTC_I0255_SPLIT-PRICE_GRP =
ZQTCV_I0255_SPLT-PRICE_GRP .
ZQTC_I0255_SPLIT-SHIP_TO_CODE =
ZQTCV_I0255_SPLT-SHIP_TO_CODE .
ZQTC_I0255_SPLIT-SOCIETY_GRP_CODE =
ZQTCV_I0255_SPLT-SOCIETY_GRP_CODE .
ZQTC_I0255_SPLIT-REASON_CODE =
ZQTCV_I0255_SPLT-REASON_CODE .
ZQTC_I0255_SPLIT-SUBSCRIPTION_CLS =
ZQTCV_I0255_SPLT-SUBSCRIPTION_CLS .
ZQTC_I0255_SPLIT-SALES_ORG =
ZQTCV_I0255_SPLT-SALES_ORG .
ZQTC_I0255_SPLIT-CONDITION_GRP2 =
ZQTCV_I0255_SPLT-CONDITION_GRP2 .
ZQTC_I0255_SPLIT-CNTRL_CIRCULATION =
ZQTCV_I0255_SPLT-CNTRL_CIRCULATION .
ZQTC_I0255_SPLIT-VARSPLIT =
ZQTCV_I0255_SPLT-VARSPLIT .
ZQTC_I0255_SPLIT-EMAIL =
ZQTCV_I0255_SPLT-EMAIL .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_I0255_SPLIT .
    ELSE.
    INSERT ZQTC_I0255_SPLIT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_I0255_SPLT-UPD_FLAG,
STATUS_ZQTCV_I0255_SPLT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_I0255_SPLT.
  SELECT SINGLE * FROM ZQTC_I0255_SPLIT WHERE
LABLTP = ZQTCV_I0255_SPLT-LABLTP AND
VARNAME = ZQTCV_I0255_SPLT-VARNAME AND
ZSEQNO = ZQTCV_I0255_SPLT-ZSEQNO AND
MEDIA_PRODUCT = ZQTCV_I0255_SPLT-MEDIA_PRODUCT .
ZQTCV_I0255_SPLT-MANDT =
ZQTC_I0255_SPLIT-MANDT .
ZQTCV_I0255_SPLT-LABLTP =
ZQTC_I0255_SPLIT-LABLTP .
ZQTCV_I0255_SPLT-VARNAME =
ZQTC_I0255_SPLIT-VARNAME .
ZQTCV_I0255_SPLT-ZSEQNO =
ZQTC_I0255_SPLIT-ZSEQNO .
ZQTCV_I0255_SPLT-MEDIA_PRODUCT =
ZQTC_I0255_SPLIT-MEDIA_PRODUCT .
ZQTCV_I0255_SPLT-MEDIA_ISSUE =
ZQTC_I0255_SPLIT-MEDIA_ISSUE .
ZQTCV_I0255_SPLT-PRICE_GRP =
ZQTC_I0255_SPLIT-PRICE_GRP .
ZQTCV_I0255_SPLT-SHIP_TO_CODE =
ZQTC_I0255_SPLIT-SHIP_TO_CODE .
ZQTCV_I0255_SPLT-SOCIETY_GRP_CODE =
ZQTC_I0255_SPLIT-SOCIETY_GRP_CODE .
ZQTCV_I0255_SPLT-REASON_CODE =
ZQTC_I0255_SPLIT-REASON_CODE .
ZQTCV_I0255_SPLT-SUBSCRIPTION_CLS =
ZQTC_I0255_SPLIT-SUBSCRIPTION_CLS .
ZQTCV_I0255_SPLT-SALES_ORG =
ZQTC_I0255_SPLIT-SALES_ORG .
ZQTCV_I0255_SPLT-CONDITION_GRP2 =
ZQTC_I0255_SPLIT-CONDITION_GRP2 .
ZQTCV_I0255_SPLT-CNTRL_CIRCULATION =
ZQTC_I0255_SPLIT-CNTRL_CIRCULATION .
ZQTCV_I0255_SPLT-VARSPLIT =
ZQTC_I0255_SPLIT-VARSPLIT .
ZQTCV_I0255_SPLT-EMAIL =
ZQTC_I0255_SPLIT-EMAIL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_I0255_SPLT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_I0255_SPLT-LABLTP TO
ZQTC_I0255_SPLIT-LABLTP .
MOVE ZQTCV_I0255_SPLT-VARNAME TO
ZQTC_I0255_SPLIT-VARNAME .
MOVE ZQTCV_I0255_SPLT-ZSEQNO TO
ZQTC_I0255_SPLIT-ZSEQNO .
MOVE ZQTCV_I0255_SPLT-MEDIA_PRODUCT TO
ZQTC_I0255_SPLIT-MEDIA_PRODUCT .
MOVE ZQTCV_I0255_SPLT-MANDT TO
ZQTC_I0255_SPLIT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_I0255_SPLIT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_I0255_SPLIT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_I0255_SPLIT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
