*----------------------------------------------------------------------*
* PROGRAM NAME: ZQTC_IB_GOBI_ORDER_I0233_5                             *
* PROGRAM DESCRIPTION: This RFC will receive the request from GOBI     *
*          through     TIBCO, Once the request received in SAP it will *
*                      validate the data and send the overall response *
* DEVELOPER      : Rajkumar Madavoina (MRAJKUMAR)                      *
* CREATION DATE  : 20/12/2021                                          *
* OBJECT ID      : I0233.5                                             *
* TRANSPORT NUMBER(S): ED2K925270                                      *
*----------------------------------------------------------------------*
FUNCTION-POOL zqtc_fg_gobi_sap_i0233_5.     "MESSAGE-ID ..
* INCLUDE LZQTC_FG_GOBI_SAP_I0233_5D...      " Local class definition
* Types declaration
TYPES: BEGIN OF ty_error,
         error TYPE char3,
         description TYPE char100,
       END OF ty_error.
* Constant values Declarations
CONSTANTS: c_i          TYPE c LENGTH 1 VALUE 'I',
           c_sep        TYPE c LENGTH 1 VALUE ';',
           c_comma      TYPE c LENGTH 1 VALUE ',',
           c_ag         TYPE c LENGTH 2 VALUE 'AG',
           c_we         TYPE c LENGTH 2 VALUE 'WE',
           c_01         TYPE c LENGTH 2 VALUE '01',
           c_ac         TYPE c LENGTH 2 VALUE 'AC',
           c_eq         TYPE c LENGTH 2 VALUE 'EQ',
           c_ir         TYPE c LENGTH 2 VALUE 'IR',
           c_cur        TYPE c LENGTH 3 VALUE 'CUR',
           c_xpo        TYPE c LENGTH 3 VALUE 'XPO',
           c_nyp        TYPE c LENGTH 3 VALUE 'NYP',
           c_ipi        TYPE c LENGTH 3 VALUE 'IPI',
           c_dup        TYPE c LENGTH 3 VALUE 'DUP',
           c_cns        TYPE c LENGTH 3 VALUE 'CNS',
           c_ful        TYPE c LENGTH 3 VALUE 'FUL',
           c_coh        TYPE c LENGTH 3 VALUE 'COH',
           c_errorcode  TYPE c LENGTH 10    VALUE 'ERROR CODE',
           c_successcode   TYPE c LENGTH 12  VALUE 'SUCCESS CODE',
           c_successcode1  TYPE c LENGTH 13  VALUE 'SUCCESS CODE1',
           c_pricecode     TYPE c LENGTH 9  VALUE 'PRICECODE',
           c_itemcode      TYPE c LENGTH 8  VALUE 'ITEMCODE',
           c_custcode      TYPE c LENGTH 8  VALUE 'CUSTCODE',
           c_custholdcode  TYPE c LENGTH 12 VALUE 'CUSTHOLDCODE',
           c_currencycode   TYPE c LENGTH 12 VALUE 'CURRENCYCODE',
           c_duplicode     TYPE c LENGTH 9  VALUE 'DUPLICODE',
           c_geogracode    TYPE c LENGTH 10 VALUE 'GEOGRACODE',
           c_productcode   TYPE c LENGTH 11 VALUE 'PRODUCTCODE',
           c_quantitycode  TYPE c LENGTH 12 VALUE 'QUANTITYCODE',
           c_publishcode   TYPE c LENGTH 11 VALUE 'PUBLISHCODE',
           c_purchasecode  TYPE c LENGTH 12 VALUE 'PURCHASECODE',
           c_obsletecode   TYPE c LENGTH 11 VALUE 'OBSLETECODE',
           c_devid      TYPE c LENGTH 7 VALUE 'I0233.5',
           c_buyerid    TYPE c LENGTH 7 VALUE 'BUYERID',
           c_object     TYPE balobj_d    VALUE 'ZQTC',
           c_subobj     TYPE balsubobj   VALUE 'ZGOBI',
           c_idcodetype TYPE c LENGTH 10  VALUE 'IDCODETYPE',
           c_currencyercode TYPE c LENGTH 18 VALUE 'CURENCY ERROR CODE',
           c_doctype      TYPE c LENGTH 13 VALUE 'DOCUMENT TYPE',
           c_conditiontype TYPE c LENGTH 14   VALUE 'CONDITION TYPE',
           c_salesorg     TYPE c LENGTH 18 VALUE 'SALES ORGANIZATION',
           c_distchanl    TYPE c LENGTH 20 VALUE 'DISTRIBUTION CHANNEL',
           c_division     TYPE c LENGTH  8 VALUE 'DIVISION',
           c_pomethod     TYPE c LENGTH  9 VALUE 'PO METHOD',
           c_doccatog     TYPE c LENGTH 17 VALUE 'DOCUMENT CATEGORY',
           c_partnertype  TYPE c LENGTH 12 VALUE 'PARTNER TYPE',
           c_purchseoption TYPE c LENGTH 15   VALUE 'PURCHASE OPTION',
           c_mstae         TYPE c LENGTH 5  VALUE 'MSTAE',
           c_headerpriority TYPE c LENGTH 21  VALUE 'HEADER ERROR PRIORITY',
           c_itempriority TYPE c LENGTH 19  VALUE 'ITEM ERROR PRIORITY',
           c_msgtyp     TYPE c LENGTH 1 VALUE 'I',
           c_msgid      TYPE c LENGTH 20 VALUE 'ZQTC_R2',
           c_msgno      TYPE n LENGTH 3 VALUE '000',
           c_slglogdays TYPE c LENGTH 11  VALUE 'SLGLOGSDAYS',
           c_allerrors  TYPE c LENGTH 10  VALUE 'ALL ERRORS'.
" Range table declaration
DATA: ir_type           TYPE TABLE OF  zukm_s_range_bu_id_type,
      ir_idcodetype     TYPE RANGE OF ismidcodetype,
      ir_mstae          TYPE RANGE OF mstae,
      ir_currencycode   TYPE STANDARD TABLE OF fkkr_waers,
      i_constant        TYPE STANDARD TABLE OF zcaconstant,
      i_response        TYPE STANDARD TABLE OF zqtc_st_gobi_response,
      i_itemdetails     TYPE STANDARD TABLE OF zqtc_st_gobi_itemdetails,
      i_items_in        TYPE STANDARD TABLE OF bapiitemin,
      i_items_out      TYPE STANDARD TABLE OF bapiitemex,
      ir_purchaseoption TYPE RANGE OF xblnr,
      ir_header_priority TYPE RANGE OF zqtc_st_gobi_response-statuscode,
      v_header_priority LIKE LINE OF ir_header_priority,
      ir_item_priority   TYPE RANGE OF zqtc_st_gobi_response-statuscode,
      v_item_priority   LIKE LINE OF ir_item_priority,
      v_allerrors       TYPE flag,
      v_constant        TYPE zcaconstant,
      v_mstae          LIKE LINE OF ir_mstae,
      v_purchaseoption LIKE LINE OF ir_purchaseoption,
      v_type          TYPE zukm_s_range_bu_id_type,
      v_response      TYPE zqtc_st_gobi_response,
      v_buyerid       TYPE char35,
      v_idcodetype    LIKE LINE OF ir_idcodetype,
      v_shipto        TYPE kunnr,
      v_soldto        TYPE kunnr,
      v_date          TYPE aldate_del,
      v_days          TYPE i,
      v_obsletecode   TYPE char5,
      v_errorcode     TYPE char5,
      v_successcode   TYPE char5,
      v_successcode1  TYPE char5,
      v_pricecode     TYPE char5,
      v_itemcode      TYPE char5,
      v_custcode      TYPE char5,
      v_custholdcode  TYPE char5,
      v_curencyercode TYPE char5,
      v_duplicode     TYPE char5,
      v_geogracode    TYPE char5,
      v_productcode   TYPE char5,
      v_quantitycode  TYPE char5,
      v_publishcode   TYPE char5,
      v_purchasecode  TYPE char5,
      v_price         TYPE char15,
      v_output_text   TYPE char200,
      v_input_text    TYPE char200,
      v_exter         TYPE balhdr-extnumber,
      v_log_handle    TYPE balloghndl, " Application Log: Log Handle
      v_log           TYPE bal_s_log, " Application Log: Log header data
      v_msg           TYPE bal_s_msg, " Application Log: Message Data
      v_header_in     TYPE bapisdhead,
      v_return        TYPE bapireturn,
      v_sold          TYPE bapisoldto,
      v_ship          TYPE bapishipto,
      v_bill          TYPE bapipayer,

      v_items_in      TYPE bapiitemin,
      i_partner       TYPE STANDARD TABLE OF bapipartnr,
      v_partner       TYPE bapipartnr,
      i_conditions_ex TYPE STANDARD TABLE OF  bapicond,
      v_conditions_ex TYPE bapicond,

      v_currencycode  TYPE fkkr_waers,
      v_doctype       TYPE auart,
      v_salesorg      TYPE vkorg,
      v_distchanl     TYPE vtweg,
      v_division      TYPE spart,
      v_pomethod      TYPE bsark,
      v_conditiontype TYPE kscha,
      v_doccatog      TYPE vbtyp,
      v_slglogdays    TYPE char3.
