*&---------------------------------------------------------------------*
*&  Include           ZQTCN_MAINTAIN_REPDET_TABL_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE text-s01.
SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE text-s02.
PARAMETERS:
  p_vkorg TYPE vbak-vkorg OBLIGATORY,
  p_vtweg TYPE vbak-vtweg OBLIGATORY,
  p_spart TYPE vbak-spart OBLIGATORY,
* BOC: CR#7764 KKRAVURI20181025  ED2K913679
  p_bsark TYPE bsark AS LISTBOX VISIBLE LENGTH 10,
* EOC: CR#7764 KKRAVURI20181025  ED2K913679
  p_datum TYPE sydatum    DEFAULT sy-datum NO-DISPLAY.
SELECTION-SCREEN END OF BLOCK b2.
SELECTION-SCREEN BEGIN OF BLOCK b6 WITH FRAME TITLE text-s06.
PARAMETERS:
  cb_allf AS CHECKBOX USER-COMMAND allf.

SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE text-s03.
PARAMETERS:
  rb_prod TYPE char1 RADIOBUTTON GROUP prd MODIF ID prd DEFAULT 'X',
  rb_prft TYPE char1 RADIOBUTTON GROUP prd MODIF ID prd,
  rb_dprd TYPE char1 RADIOBUTTON GROUP prd MODIF ID prd.
SELECTION-SCREEN END OF BLOCK b3.
SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME TITLE text-s04.
PARAMETERS:
  rb_bpid TYPE char1 RADIOBUTTON GROUP ind MODIF ID ind DEFAULT 'X'
                     USER-COMMAND bpid,
* BOC: CR#7764 KKRAVURI20181025  ED2K913679
  rb_sp   TYPE char1 RADIOBUTTON GROUP ind MODIF ID ind,
* EOC: CR#7764 KKRAVURI20181025  ED2K913679
  rb_cgrp TYPE char1 RADIOBUTTON GROUP ind MODIF ID ind,
  rb_dind TYPE char1 RADIOBUTTON GROUP ind MODIF ID ind.
SELECTION-SCREEN END OF BLOCK b4.
SELECTION-SCREEN BEGIN OF BLOCK b5 WITH FRAME TITLE text-s05.
PARAMETERS:
  rb_pcds TYPE char1 RADIOBUTTON GROUP geo MODIF ID geo DEFAULT 'X',
  rb_pcdr TYPE char1 RADIOBUTTON GROUP geo MODIF ID geo,
  rb_regn TYPE char1 RADIOBUTTON GROUP geo MODIF ID geo,
  rb_land TYPE char1 RADIOBUTTON GROUP geo MODIF ID geo,
  rb_dgeo TYPE char1 RADIOBUTTON GROUP geo MODIF ID geo.
SELECTION-SCREEN END OF BLOCK b5.
SELECTION-SCREEN END OF BLOCK b6.
SELECTION-SCREEN END OF BLOCK b1.
