FUNCTION ZCALCULATE_CHECK_DIGIT_MOD11.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(NUMBER_PART) TYPE  C
*"  EXPORTING
*"     VALUE(CHECK_DIGIT) TYPE  C
*"--------------------------------------------------------------------

DATA: LENGTH TYPE I, MULT1 TYPE N, MULT2 TYPE N VALUE 2,
      PROD(2) TYPE N, ADDI TYPE P VALUE 0, MODU(1) TYPE N, REST TYPE P.
DATA: WORK_STRING(50) TYPE C.

WORK_STRING = NUMBER_PART.

LENGTH = STRLEN( WORK_STRING ).

SHIFT WORK_STRING RIGHT DELETING TRAILING SPACE.
*CONDENSE WORK_STRING.
DO LENGTH TIMES.
   SHIFT WORK_STRING RIGHT CIRCULAR.
   WRITE WORK_STRING(1) TO MULT1.
   PROD = MULT1 * MULT2.
   ADDI = ADDI  + PROD."PROD(1) + PROD+1(1).
   IF MULT2 = 7.
     MULT2 = 2.
   ELSE.
     MULT2 =  MULT2 + 1.
   ENDIF.
ENDDO.

REST = ADDI MOD 11.

MODU = ( 11 - REST ) MOD 11.

CHECK_DIGIT = MODU.

ENDFUNCTION.
