*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_RENWL_PLAN................................*
FORM GET_DATA_ZQTCV_RENWL_PLAN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_RENWL_PLAN WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_RENWL_PLAN .
ZQTCV_RENWL_PLAN-MANDT =
ZQTC_RENWL_PLAN-MANDT .
ZQTCV_RENWL_PLAN-VBELN =
ZQTC_RENWL_PLAN-VBELN .
ZQTCV_RENWL_PLAN-POSNR =
ZQTC_RENWL_PLAN-POSNR .
ZQTCV_RENWL_PLAN-ACTIVITY =
ZQTC_RENWL_PLAN-ACTIVITY .
ZQTCV_RENWL_PLAN-MATNR =
ZQTC_RENWL_PLAN-MATNR .
ZQTCV_RENWL_PLAN-EADAT =
ZQTC_RENWL_PLAN-EADAT .
ZQTCV_RENWL_PLAN-RENWL_PROF =
ZQTC_RENWL_PLAN-RENWL_PROF .
ZQTCV_RENWL_PLAN-PROMO_CODE =
ZQTC_RENWL_PLAN-PROMO_CODE .
ZQTCV_RENWL_PLAN-ACT_STATUS =
ZQTC_RENWL_PLAN-ACT_STATUS .
ZQTCV_RENWL_PLAN-REN_STATUS =
ZQTC_RENWL_PLAN-REN_STATUS .
ZQTCV_RENWL_PLAN-EXCL_RESN =
ZQTC_RENWL_PLAN-EXCL_RESN .
ZQTCV_RENWL_PLAN-EXCL_DATE =
ZQTC_RENWL_PLAN-EXCL_DATE .
ZQTCV_RENWL_PLAN-AENAM =
ZQTC_RENWL_PLAN-AENAM .
ZQTCV_RENWL_PLAN-AEDAT =
ZQTC_RENWL_PLAN-AEDAT .
ZQTCV_RENWL_PLAN-AEZET =
ZQTC_RENWL_PLAN-AEZET .
    SELECT SINGLE * FROM ZQTC_ACTIVITY WHERE
ACTIVITY = ZQTC_RENWL_PLAN-ACTIVITY .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_ACTIVITY WHERE
ACTIVITY = ZQTC_ACTIVITY-ACTIVITY AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PLAN-ACTIVITY_D =
ZQTCT_ACTIVITY-ACTIVITY_D .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PLAN-RENWL_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PLAN-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZQTC_EXCL_RESN WHERE
EXCL_RESN = ZQTC_RENWL_PLAN-EXCL_RESN .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_EXCL_RESN WHERE
EXCL_RESN = ZQTC_EXCL_RESN-EXCL_RESN AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PLAN-EXCL_RESN_D =
ZQTCT_EXCL_RESN-EXCL_RESN_D .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_RENWL_PLAN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_RENWL_PLAN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_RENWL_PLAN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_RENWL_PLAN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RENWL_PLAN WHERE
  VBELN = ZQTCV_RENWL_PLAN-VBELN AND
  POSNR = ZQTCV_RENWL_PLAN-POSNR AND
  ACTIVITY = ZQTCV_RENWL_PLAN-ACTIVITY .
    IF SY-SUBRC = 0.
    DELETE ZQTC_RENWL_PLAN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_RENWL_PLAN WHERE
  VBELN = ZQTCV_RENWL_PLAN-VBELN AND
  POSNR = ZQTCV_RENWL_PLAN-POSNR AND
  ACTIVITY = ZQTCV_RENWL_PLAN-ACTIVITY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_RENWL_PLAN.
    ENDIF.
ZQTC_RENWL_PLAN-MANDT =
ZQTCV_RENWL_PLAN-MANDT .
ZQTC_RENWL_PLAN-VBELN =
ZQTCV_RENWL_PLAN-VBELN .
ZQTC_RENWL_PLAN-POSNR =
ZQTCV_RENWL_PLAN-POSNR .
ZQTC_RENWL_PLAN-ACTIVITY =
ZQTCV_RENWL_PLAN-ACTIVITY .
ZQTC_RENWL_PLAN-MATNR =
ZQTCV_RENWL_PLAN-MATNR .
ZQTC_RENWL_PLAN-EADAT =
ZQTCV_RENWL_PLAN-EADAT .
ZQTC_RENWL_PLAN-RENWL_PROF =
ZQTCV_RENWL_PLAN-RENWL_PROF .
ZQTC_RENWL_PLAN-PROMO_CODE =
ZQTCV_RENWL_PLAN-PROMO_CODE .
ZQTC_RENWL_PLAN-ACT_STATUS =
ZQTCV_RENWL_PLAN-ACT_STATUS .
ZQTC_RENWL_PLAN-REN_STATUS =
ZQTCV_RENWL_PLAN-REN_STATUS .
ZQTC_RENWL_PLAN-EXCL_RESN =
ZQTCV_RENWL_PLAN-EXCL_RESN .
ZQTC_RENWL_PLAN-EXCL_DATE =
ZQTCV_RENWL_PLAN-EXCL_DATE .
ZQTC_RENWL_PLAN-AENAM =
ZQTCV_RENWL_PLAN-AENAM .
ZQTC_RENWL_PLAN-AEDAT =
ZQTCV_RENWL_PLAN-AEDAT .
ZQTC_RENWL_PLAN-AEZET =
ZQTCV_RENWL_PLAN-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_RENWL_PLAN .
    ELSE.
    INSERT ZQTC_RENWL_PLAN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_RENWL_PLAN-UPD_FLAG,
STATUS_ZQTCV_RENWL_PLAN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_RENWL_PLAN.
  SELECT SINGLE * FROM ZQTC_RENWL_PLAN WHERE
VBELN = ZQTCV_RENWL_PLAN-VBELN AND
POSNR = ZQTCV_RENWL_PLAN-POSNR AND
ACTIVITY = ZQTCV_RENWL_PLAN-ACTIVITY .
ZQTCV_RENWL_PLAN-MANDT =
ZQTC_RENWL_PLAN-MANDT .
ZQTCV_RENWL_PLAN-VBELN =
ZQTC_RENWL_PLAN-VBELN .
ZQTCV_RENWL_PLAN-POSNR =
ZQTC_RENWL_PLAN-POSNR .
ZQTCV_RENWL_PLAN-ACTIVITY =
ZQTC_RENWL_PLAN-ACTIVITY .
ZQTCV_RENWL_PLAN-MATNR =
ZQTC_RENWL_PLAN-MATNR .
ZQTCV_RENWL_PLAN-EADAT =
ZQTC_RENWL_PLAN-EADAT .
ZQTCV_RENWL_PLAN-RENWL_PROF =
ZQTC_RENWL_PLAN-RENWL_PROF .
ZQTCV_RENWL_PLAN-PROMO_CODE =
ZQTC_RENWL_PLAN-PROMO_CODE .
ZQTCV_RENWL_PLAN-ACT_STATUS =
ZQTC_RENWL_PLAN-ACT_STATUS .
ZQTCV_RENWL_PLAN-REN_STATUS =
ZQTC_RENWL_PLAN-REN_STATUS .
ZQTCV_RENWL_PLAN-EXCL_RESN =
ZQTC_RENWL_PLAN-EXCL_RESN .
ZQTCV_RENWL_PLAN-EXCL_DATE =
ZQTC_RENWL_PLAN-EXCL_DATE .
ZQTCV_RENWL_PLAN-AENAM =
ZQTC_RENWL_PLAN-AENAM .
ZQTCV_RENWL_PLAN-AEDAT =
ZQTC_RENWL_PLAN-AEDAT .
ZQTCV_RENWL_PLAN-AEZET =
ZQTC_RENWL_PLAN-AEZET .
    SELECT SINGLE * FROM ZQTC_ACTIVITY WHERE
ACTIVITY = ZQTC_RENWL_PLAN-ACTIVITY .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_ACTIVITY WHERE
ACTIVITY = ZQTC_ACTIVITY-ACTIVITY AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PLAN-ACTIVITY_D =
ZQTCT_ACTIVITY-ACTIVITY_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PLAN-ACTIVITY_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PLAN-ACTIVITY_D .
    ENDIF.
    SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PLAN-RENWL_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PLAN-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PLAN-RENWL_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PLAN-RENWL_PROF_D .
    ENDIF.
    SELECT SINGLE * FROM ZQTC_EXCL_RESN WHERE
EXCL_RESN = ZQTC_RENWL_PLAN-EXCL_RESN .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_EXCL_RESN WHERE
EXCL_RESN = ZQTC_EXCL_RESN-EXCL_RESN AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PLAN-EXCL_RESN_D =
ZQTCT_EXCL_RESN-EXCL_RESN_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PLAN-EXCL_RESN_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PLAN-EXCL_RESN_D .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_RENWL_PLAN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_RENWL_PLAN-VBELN TO
ZQTC_RENWL_PLAN-VBELN .
MOVE ZQTCV_RENWL_PLAN-POSNR TO
ZQTC_RENWL_PLAN-POSNR .
MOVE ZQTCV_RENWL_PLAN-ACTIVITY TO
ZQTC_RENWL_PLAN-ACTIVITY .
MOVE ZQTCV_RENWL_PLAN-MANDT TO
ZQTC_RENWL_PLAN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_RENWL_PLAN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_RENWL_PLAN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_RENWL_PLAN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZQTCV_RENWL_PLAN USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZQTC_RENWL_PLAN-MANDT =
ZQTCV_RENWL_PLAN-MANDT .
ZQTC_RENWL_PLAN-VBELN =
ZQTCV_RENWL_PLAN-VBELN .
ZQTC_RENWL_PLAN-POSNR =
ZQTCV_RENWL_PLAN-POSNR .
ZQTC_RENWL_PLAN-ACTIVITY =
ZQTCV_RENWL_PLAN-ACTIVITY .
ZQTC_RENWL_PLAN-MATNR =
ZQTCV_RENWL_PLAN-MATNR .
ZQTC_RENWL_PLAN-EADAT =
ZQTCV_RENWL_PLAN-EADAT .
ZQTC_RENWL_PLAN-RENWL_PROF =
ZQTCV_RENWL_PLAN-RENWL_PROF .
ZQTC_RENWL_PLAN-PROMO_CODE =
ZQTCV_RENWL_PLAN-PROMO_CODE .
ZQTC_RENWL_PLAN-ACT_STATUS =
ZQTCV_RENWL_PLAN-ACT_STATUS .
ZQTC_RENWL_PLAN-REN_STATUS =
ZQTCV_RENWL_PLAN-REN_STATUS .
ZQTC_RENWL_PLAN-EXCL_RESN =
ZQTCV_RENWL_PLAN-EXCL_RESN .
ZQTC_RENWL_PLAN-EXCL_DATE =
ZQTCV_RENWL_PLAN-EXCL_DATE .
ZQTC_RENWL_PLAN-AENAM =
ZQTCV_RENWL_PLAN-AENAM .
ZQTC_RENWL_PLAN-AEDAT =
ZQTCV_RENWL_PLAN-AEDAT .
ZQTC_RENWL_PLAN-AEZET =
ZQTCV_RENWL_PLAN-AEZET .
    SELECT SINGLE * FROM ZQTC_ACTIVITY WHERE
ACTIVITY = ZQTC_RENWL_PLAN-ACTIVITY .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_ACTIVITY WHERE
ACTIVITY = ZQTC_ACTIVITY-ACTIVITY AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PLAN-ACTIVITY_D =
ZQTCT_ACTIVITY-ACTIVITY_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PLAN-ACTIVITY_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PLAN-ACTIVITY_D .
    ENDIF.
    SELECT SINGLE * FROM ZQTC_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PLAN-RENWL_PROF .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_RENWL_PROF WHERE
RENWL_PROF = ZQTC_RENWL_PROF-RENWL_PROF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PLAN-RENWL_PROF_D =
ZQTCT_RENWL_PROF-RENWL_PROF_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PLAN-RENWL_PROF_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PLAN-RENWL_PROF_D .
    ENDIF.
    SELECT SINGLE * FROM ZQTC_EXCL_RESN WHERE
EXCL_RESN = ZQTC_RENWL_PLAN-EXCL_RESN .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZQTCT_EXCL_RESN WHERE
EXCL_RESN = ZQTC_EXCL_RESN-EXCL_RESN AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZQTCV_RENWL_PLAN-EXCL_RESN_D =
ZQTCT_EXCL_RESN-EXCL_RESN_D .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZQTCV_RENWL_PLAN-EXCL_RESN_D .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_RENWL_PLAN-EXCL_RESN_D .
    ENDIF.
ENDFORM.
