*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVQTC_REPDET....................................*
FORM GET_DATA_ZVQTC_REPDET.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_REPDET WHERE
(VIM_WHERETAB) .
    CLEAR ZVQTC_REPDET .
ZVQTC_REPDET-MANDT =
ZQTC_REPDET-MANDT .
ZVQTC_REPDET-VKORG =
ZQTC_REPDET-VKORG .
ZVQTC_REPDET-VTWEG =
ZQTC_REPDET-VTWEG .
ZVQTC_REPDET-SPART =
ZQTC_REPDET-SPART .
ZVQTC_REPDET-BSARK =
ZQTC_REPDET-BSARK .
ZVQTC_REPDET-MATNR =
ZQTC_REPDET-MATNR .
ZVQTC_REPDET-PRCTR =
ZQTC_REPDET-PRCTR .
ZVQTC_REPDET-KUNNR =
ZQTC_REPDET-KUNNR .
ZVQTC_REPDET-KVGR1 =
ZQTC_REPDET-KVGR1 .
ZVQTC_REPDET-PSTLZ_F =
ZQTC_REPDET-PSTLZ_F .
ZVQTC_REPDET-PSTLZ_T =
ZQTC_REPDET-PSTLZ_T .
ZVQTC_REPDET-REGIO =
ZQTC_REPDET-REGIO .
ZVQTC_REPDET-LAND1 =
ZQTC_REPDET-LAND1 .
ZVQTC_REPDET-DATAB =
ZQTC_REPDET-DATAB .
ZVQTC_REPDET-ZSHIP_TO =
ZQTC_REPDET-ZSHIP_TO .
ZVQTC_REPDET-DATBI =
ZQTC_REPDET-DATBI .
ZVQTC_REPDET-SREP1 =
ZQTC_REPDET-SREP1 .
ZVQTC_REPDET-SREP2 =
ZQTC_REPDET-SREP2 .
ZVQTC_REPDET-AENAM =
ZQTC_REPDET-AENAM .
ZVQTC_REPDET-AEDAT =
ZQTC_REPDET-AEDAT .
ZVQTC_REPDET-AEZET =
ZQTC_REPDET-AEZET .
<VIM_TOTAL_STRUC> = ZVQTC_REPDET.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVQTC_REPDET .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVQTC_REPDET.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVQTC_REPDET-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_REPDET WHERE
  VKORG = ZVQTC_REPDET-VKORG AND
  VTWEG = ZVQTC_REPDET-VTWEG AND
  SPART = ZVQTC_REPDET-SPART AND
  BSARK = ZVQTC_REPDET-BSARK AND
  MATNR = ZVQTC_REPDET-MATNR AND
  PRCTR = ZVQTC_REPDET-PRCTR AND
  KUNNR = ZVQTC_REPDET-KUNNR AND
  KVGR1 = ZVQTC_REPDET-KVGR1 AND
  PSTLZ_F = ZVQTC_REPDET-PSTLZ_F AND
  PSTLZ_T = ZVQTC_REPDET-PSTLZ_T AND
  REGIO = ZVQTC_REPDET-REGIO AND
  LAND1 = ZVQTC_REPDET-LAND1 AND
  DATAB = ZVQTC_REPDET-DATAB AND
  ZSHIP_TO = ZVQTC_REPDET-ZSHIP_TO .
    IF SY-SUBRC = 0.
    DELETE ZQTC_REPDET .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_REPDET WHERE
  VKORG = ZVQTC_REPDET-VKORG AND
  VTWEG = ZVQTC_REPDET-VTWEG AND
  SPART = ZVQTC_REPDET-SPART AND
  BSARK = ZVQTC_REPDET-BSARK AND
  MATNR = ZVQTC_REPDET-MATNR AND
  PRCTR = ZVQTC_REPDET-PRCTR AND
  KUNNR = ZVQTC_REPDET-KUNNR AND
  KVGR1 = ZVQTC_REPDET-KVGR1 AND
  PSTLZ_F = ZVQTC_REPDET-PSTLZ_F AND
  PSTLZ_T = ZVQTC_REPDET-PSTLZ_T AND
  REGIO = ZVQTC_REPDET-REGIO AND
  LAND1 = ZVQTC_REPDET-LAND1 AND
  DATAB = ZVQTC_REPDET-DATAB AND
  ZSHIP_TO = ZVQTC_REPDET-ZSHIP_TO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_REPDET.
    ENDIF.
ZQTC_REPDET-MANDT =
ZVQTC_REPDET-MANDT .
ZQTC_REPDET-VKORG =
ZVQTC_REPDET-VKORG .
ZQTC_REPDET-VTWEG =
ZVQTC_REPDET-VTWEG .
ZQTC_REPDET-SPART =
ZVQTC_REPDET-SPART .
ZQTC_REPDET-BSARK =
ZVQTC_REPDET-BSARK .
ZQTC_REPDET-MATNR =
ZVQTC_REPDET-MATNR .
ZQTC_REPDET-PRCTR =
ZVQTC_REPDET-PRCTR .
ZQTC_REPDET-KUNNR =
ZVQTC_REPDET-KUNNR .
ZQTC_REPDET-KVGR1 =
ZVQTC_REPDET-KVGR1 .
ZQTC_REPDET-PSTLZ_F =
ZVQTC_REPDET-PSTLZ_F .
ZQTC_REPDET-PSTLZ_T =
ZVQTC_REPDET-PSTLZ_T .
ZQTC_REPDET-REGIO =
ZVQTC_REPDET-REGIO .
ZQTC_REPDET-LAND1 =
ZVQTC_REPDET-LAND1 .
ZQTC_REPDET-DATAB =
ZVQTC_REPDET-DATAB .
ZQTC_REPDET-ZSHIP_TO =
ZVQTC_REPDET-ZSHIP_TO .
ZQTC_REPDET-DATBI =
ZVQTC_REPDET-DATBI .
ZQTC_REPDET-SREP1 =
ZVQTC_REPDET-SREP1 .
ZQTC_REPDET-SREP2 =
ZVQTC_REPDET-SREP2 .
ZQTC_REPDET-AENAM =
ZVQTC_REPDET-AENAM .
ZQTC_REPDET-AEDAT =
ZVQTC_REPDET-AEDAT .
ZQTC_REPDET-AEZET =
ZVQTC_REPDET-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_REPDET .
    ELSE.
    INSERT ZQTC_REPDET .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVQTC_REPDET-UPD_FLAG,
STATUS_ZVQTC_REPDET-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVQTC_REPDET.
  SELECT SINGLE * FROM ZQTC_REPDET WHERE
VKORG = ZVQTC_REPDET-VKORG AND
VTWEG = ZVQTC_REPDET-VTWEG AND
SPART = ZVQTC_REPDET-SPART AND
BSARK = ZVQTC_REPDET-BSARK AND
MATNR = ZVQTC_REPDET-MATNR AND
PRCTR = ZVQTC_REPDET-PRCTR AND
KUNNR = ZVQTC_REPDET-KUNNR AND
KVGR1 = ZVQTC_REPDET-KVGR1 AND
PSTLZ_F = ZVQTC_REPDET-PSTLZ_F AND
PSTLZ_T = ZVQTC_REPDET-PSTLZ_T AND
REGIO = ZVQTC_REPDET-REGIO AND
LAND1 = ZVQTC_REPDET-LAND1 AND
DATAB = ZVQTC_REPDET-DATAB AND
ZSHIP_TO = ZVQTC_REPDET-ZSHIP_TO .
ZVQTC_REPDET-MANDT =
ZQTC_REPDET-MANDT .
ZVQTC_REPDET-VKORG =
ZQTC_REPDET-VKORG .
ZVQTC_REPDET-VTWEG =
ZQTC_REPDET-VTWEG .
ZVQTC_REPDET-SPART =
ZQTC_REPDET-SPART .
ZVQTC_REPDET-BSARK =
ZQTC_REPDET-BSARK .
ZVQTC_REPDET-MATNR =
ZQTC_REPDET-MATNR .
ZVQTC_REPDET-PRCTR =
ZQTC_REPDET-PRCTR .
ZVQTC_REPDET-KUNNR =
ZQTC_REPDET-KUNNR .
ZVQTC_REPDET-KVGR1 =
ZQTC_REPDET-KVGR1 .
ZVQTC_REPDET-PSTLZ_F =
ZQTC_REPDET-PSTLZ_F .
ZVQTC_REPDET-PSTLZ_T =
ZQTC_REPDET-PSTLZ_T .
ZVQTC_REPDET-REGIO =
ZQTC_REPDET-REGIO .
ZVQTC_REPDET-LAND1 =
ZQTC_REPDET-LAND1 .
ZVQTC_REPDET-DATAB =
ZQTC_REPDET-DATAB .
ZVQTC_REPDET-ZSHIP_TO =
ZQTC_REPDET-ZSHIP_TO .
ZVQTC_REPDET-DATBI =
ZQTC_REPDET-DATBI .
ZVQTC_REPDET-SREP1 =
ZQTC_REPDET-SREP1 .
ZVQTC_REPDET-SREP2 =
ZQTC_REPDET-SREP2 .
ZVQTC_REPDET-AENAM =
ZQTC_REPDET-AENAM .
ZVQTC_REPDET-AEDAT =
ZQTC_REPDET-AEDAT .
ZVQTC_REPDET-AEZET =
ZQTC_REPDET-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVQTC_REPDET USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVQTC_REPDET-VKORG TO
ZQTC_REPDET-VKORG .
MOVE ZVQTC_REPDET-VTWEG TO
ZQTC_REPDET-VTWEG .
MOVE ZVQTC_REPDET-SPART TO
ZQTC_REPDET-SPART .
MOVE ZVQTC_REPDET-BSARK TO
ZQTC_REPDET-BSARK .
MOVE ZVQTC_REPDET-MATNR TO
ZQTC_REPDET-MATNR .
MOVE ZVQTC_REPDET-PRCTR TO
ZQTC_REPDET-PRCTR .
MOVE ZVQTC_REPDET-KUNNR TO
ZQTC_REPDET-KUNNR .
MOVE ZVQTC_REPDET-KVGR1 TO
ZQTC_REPDET-KVGR1 .
MOVE ZVQTC_REPDET-PSTLZ_F TO
ZQTC_REPDET-PSTLZ_F .
MOVE ZVQTC_REPDET-PSTLZ_T TO
ZQTC_REPDET-PSTLZ_T .
MOVE ZVQTC_REPDET-REGIO TO
ZQTC_REPDET-REGIO .
MOVE ZVQTC_REPDET-LAND1 TO
ZQTC_REPDET-LAND1 .
MOVE ZVQTC_REPDET-DATAB TO
ZQTC_REPDET-DATAB .
MOVE ZVQTC_REPDET-ZSHIP_TO TO
ZQTC_REPDET-ZSHIP_TO .
MOVE ZVQTC_REPDET-MANDT TO
ZQTC_REPDET-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_REPDET'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_REPDET TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_REPDET'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
