*---------------------------------------------------------------------*
*PROGRAM NAME :  ZQTCR_MED_ISS_R115_SEL_New(Include Program)
* PROGRAM DESCRIPTION: Media Issue Cockpit
* DEVELOPER: Krishna Srikanth J (KSRIKANTH)
* CREATION DATE:   12 July, 2021
* OBJECT ID:  R115
* REFERENCE NO: OTCM-45437
* TRANSPORT NUMBER(S):ED2K924056
* DESCRIPTION : Media Issue cockpit dashboard selection-screen field changes
"        and copied from Old cockpit program*
*&---------------------------------------------------------------------*
*----------------------------------------------------------------------*
* REVISION NO :
* REFERENCE NO:
* DEVELOPER   :
* DATE        :
* DESCRIPTION :
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b17 WITH FRAME TITLE text-011.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: rb_fgr RADIOBUTTON GROUP grp1 DEFAULT 'X' USER-COMMAND uc1.  " Radio button for Summary report
SELECTION-SCREEN COMMENT 16(15) text-012 FOR FIELD rb_fgr .
PARAMETERS: rb_bgr RADIOBUTTON GROUP grp1 .
SELECTION-SCREEN COMMENT 36(15) text-013 FOR FIELD rb_bgr .               " Radio button for detail report
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK b17.

*Block for Media Master Data
SELECTION-SCREEN BEGIN OF BLOCK bl1 WITH FRAME TITLE text-001.
SELECT-OPTIONS :
             s_prod   FOR jksesched-product,
             s_issu   FOR jksesched-issue,
             s_pbdt   FOR mara-ismpubldate,
             s_indt   FOR mara-isminitshipdate,
             s_dldt   FOR jksenip-shipping_date,
             s_gddt   FOR marc-ismarrivaldateac.
SELECTION-SCREEN END OF BLOCK bl1.

*Block for Organization Data
SELECTION-SCREEN BEGIN OF BLOCK bl2 WITH FRAME TITLE text-002.
SELECT-OPTIONS:
             s_sorg   FOR vbak-vkorg, " OBLIGATORY,
             s_dist   FOR vbak-vtweg, " DEFAULT '00',
             s_sdiv   FOR vbak-spart, "DEFAULT '00',
             s_soff   FOR vbak-vkbur.
SELECTION-SCREEN END OF BLOCK bl2.

*Block for Document Data
SELECTION-SCREEN BEGIN OF BLOCK bl3 WITH FRAME TITLE text-003.
SELECT-OPTIONS:
             s_sdoc   FOR vbak-vbeln, " OBLIGATORY,
             s_assg   FOR zcds_mi_r115_rpt-assignment,
             s_dctp   FOR vbak-auart, " DEFAULT '00',
             s_itcg   FOR vbap-pstyv,
             s_csdt   FOR zcds_mi_r115_rpt-contract_start_date,
             s_cedt   FOR zcds_mi_r115_rpt-contract_end_date,
             s_rele   FOR jkseflow-vbelnorder.
"s_vdat   FOR zcds_mi_r115_rpt-contract_start_date.
SELECTION-SCREEN END OF BLOCK bl3.

* Display Unearned Record
SELECTION-SCREEN BEGIN OF BLOCK bl5 WITH FRAME TITLE text-005.
SELECTION-SCREEN: BEGIN OF LINE.
**COMMENT 1(1)  text-s10." FOR FIELD rbg.
*PARAMETERS : rbg   RADIOBUTTON GROUP a1 ."MODIF ID m1.
***PARAMETERS : c_rbg   AS CHECKBOX USER-COMMAND a1."MODIF ID m1.
PARAMETERS : c_rbg NO-DISPLAY.
SELECTION-SCREEN COMMENT 1(30) text-s08 FOR FIELD c_rbg.
PARAMETERS : rbg1  RADIOBUTTON GROUP a1 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 38(4) FOR FIELD rbg1.
PARAMETERS : rbg2  RADIOBUTTON GROUP a1 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 44(2) FOR FIELD rbg2.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK bl5.

SELECTION-SCREEN BEGIN OF BLOCK bl4 WITH FRAME TITLE text-004.

SELECTION-SCREEN: BEGIN OF LINE.
**COMMENT 1(1) text-s10.
***PARAMETERS: c_exbb AS CHECKBOX USER-COMMAND g1.
PARAMETERS: c_exbb NO-DISPLAY.
SELECTION-SCREEN COMMENT 1(30) text-s01 FOR FIELD c_exbb.
PARAMETERS : rb1  RADIOBUTTON GROUP g1 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 38(4) FOR FIELD rb1.
PARAMETERS : rb2  RADIOBUTTON GROUP g1 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 44(2) FOR FIELD rb2.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
**COMMENT 1(1) text-s10.
***PARAMETERS: c_exdb AS CHECKBOX USER-COMMAND g2.
PARAMETERS: c_exdb NO-DISPLAY.
SELECTION-SCREEN COMMENT 1(30) text-s02 FOR FIELD c_exdb.
PARAMETERS : rb3  RADIOBUTTON GROUP g2 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 38(4) FOR FIELD rb3.
PARAMETERS : rb4  RADIOBUTTON GROUP g2 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 44(2) FOR FIELD rb4.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
**COMMENT 1(1) text-s10.
***PARAMETERS: c_excb AS CHECKBOX USER-COMMAND g3.
PARAMETERS: c_excb NO-DISPLAY.
SELECTION-SCREEN COMMENT 1(30) text-s04 FOR FIELD c_excb.
PARAMETERS : rb5  RADIOBUTTON GROUP g3 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 38(4) FOR FIELD rb5.
PARAMETERS : rb6  RADIOBUTTON GROUP g3 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 44(2) FOR FIELD rb6.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
**COMMENT 1(1) text-s10.
***PARAMETERS: c_excc AS CHECKBOX USER-COMMAND g4.
PARAMETERS: c_excc NO-DISPLAY.
SELECTION-SCREEN COMMENT 1(30) text-s05 FOR FIELD c_excc.
PARAMETERS : rb7  RADIOBUTTON GROUP g4 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 38(4) FOR FIELD rb7.
PARAMETERS : rb8  RADIOBUTTON GROUP g4 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 44(2) FOR FIELD rb8.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
**COMMENT 1(1) text-s10.
***PARAMETERS: c_exro AS CHECKBOX USER-COMMAND g5.
PARAMETERS: c_exro NO-DISPLAY.
SELECTION-SCREEN COMMENT 1(30) text-s06 FOR FIELD c_exro.
PARAMETERS : rb9  RADIOBUTTON GROUP g5 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 38(4) FOR FIELD rb9.
PARAMETERS : rb10  RADIOBUTTON GROUP g5 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 44(2) FOR FIELD rb10.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: BEGIN OF LINE.
**COMMENT 1(1) text-s10.
***PARAMETERS: c_irel AS CHECKBOX USER-COMMAND g6.
PARAMETERS: c_irel NO-DISPLAY.
SELECTION-SCREEN COMMENT 1(30) text-s07 FOR FIELD c_irel.
PARAMETERS : rb11  RADIOBUTTON GROUP g6 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 38(4) FOR FIELD rb11.
PARAMETERS : rb12  RADIOBUTTON GROUP g6 ."MODIF ID m1.
SELECTION-SCREEN COMMENT 44(2) FOR FIELD rb12.
SELECTION-SCREEN: END OF LINE.

*tables: vbuk.

SELECTION-SCREEN END OF BLOCK bl4.

SELECTION-SCREEN BEGIN OF BLOCK b16 WITH FRAME TITLE text-006.
PARAMETERS : p_alv_vr TYPE slis_vari OBLIGATORY, " Layout
             p_userid TYPE sy-uname  NO-DISPLAY. " GUI user
SELECTION-SCREEN END OF BLOCK b16.
