*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZQTCV_PROD_GROUP................................*
FORM GET_DATA_ZQTCV_PROD_GROUP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_PROD_GROUP WHERE
(VIM_WHERETAB) .
    CLEAR ZQTCV_PROD_GROUP .
ZQTCV_PROD_GROUP-MANDT =
ZQTC_PROD_GROUP-MANDT .
ZQTCV_PROD_GROUP-PROD_GROUP =
ZQTC_PROD_GROUP-PROD_GROUP .
    SELECT SINGLE * FROM ZQTCT_PROD_GROUP WHERE
PROD_GROUP = ZQTC_PROD_GROUP-PROD_GROUP AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZQTCV_PROD_GROUP-PROD_GROUP_D =
ZQTCT_PROD_GROUP-PROD_GROUP_D .
    ENDIF.
<VIM_TOTAL_STRUC> = ZQTCV_PROD_GROUP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZQTCV_PROD_GROUP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZQTCV_PROD_GROUP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZQTCV_PROD_GROUP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_PROD_GROUP WHERE
  PROD_GROUP = ZQTCV_PROD_GROUP-PROD_GROUP .
    IF SY-SUBRC = 0.
    DELETE ZQTC_PROD_GROUP .
    ENDIF.
    DELETE FROM ZQTCT_PROD_GROUP WHERE
    PROD_GROUP = ZQTC_PROD_GROUP-PROD_GROUP .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_PROD_GROUP WHERE
  PROD_GROUP = ZQTCV_PROD_GROUP-PROD_GROUP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_PROD_GROUP.
    ENDIF.
ZQTC_PROD_GROUP-MANDT =
ZQTCV_PROD_GROUP-MANDT .
ZQTC_PROD_GROUP-PROD_GROUP =
ZQTCV_PROD_GROUP-PROD_GROUP .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_PROD_GROUP .
    ELSE.
    INSERT ZQTC_PROD_GROUP .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZQTCT_PROD_GROUP WHERE
    PROD_GROUP = ZQTC_PROD_GROUP-PROD_GROUP AND
    SPRAS = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZQTCT_PROD_GROUP.
ZQTCT_PROD_GROUP-PROD_GROUP =
ZQTC_PROD_GROUP-PROD_GROUP .
ZQTCT_PROD_GROUP-SPRAS =
SY-LANGU .
      ENDIF.
ZQTCT_PROD_GROUP-PROD_GROUP_D =
ZQTCV_PROD_GROUP-PROD_GROUP_D .
    IF SY-SUBRC = 0.
    UPDATE ZQTCT_PROD_GROUP .
    ELSE.
    INSERT ZQTCT_PROD_GROUP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZQTCV_PROD_GROUP-UPD_FLAG,
STATUS_ZQTCV_PROD_GROUP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZQTCV_PROD_GROUP.
  SELECT SINGLE * FROM ZQTC_PROD_GROUP WHERE
PROD_GROUP = ZQTCV_PROD_GROUP-PROD_GROUP .
ZQTCV_PROD_GROUP-MANDT =
ZQTC_PROD_GROUP-MANDT .
ZQTCV_PROD_GROUP-PROD_GROUP =
ZQTC_PROD_GROUP-PROD_GROUP .
    SELECT SINGLE * FROM ZQTCT_PROD_GROUP WHERE
PROD_GROUP = ZQTC_PROD_GROUP-PROD_GROUP AND
SPRAS = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZQTCV_PROD_GROUP-PROD_GROUP_D =
ZQTCT_PROD_GROUP-PROD_GROUP_D .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZQTCV_PROD_GROUP-PROD_GROUP_D .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZQTCV_PROD_GROUP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZQTCV_PROD_GROUP-PROD_GROUP TO
ZQTC_PROD_GROUP-PROD_GROUP .
MOVE ZQTCV_PROD_GROUP-MANDT TO
ZQTC_PROD_GROUP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_PROD_GROUP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_PROD_GROUP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_PROD_GROUP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZQTC_PROD_GROUP-PROD_GROUP TO
ZQTCT_PROD_GROUP-PROD_GROUP .
MOVE SY-LANGU TO
ZQTCT_PROD_GROUP-SPRAS .
MOVE ZQTCV_PROD_GROUP-MANDT TO
ZQTCT_PROD_GROUP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTCT_PROD_GROUP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTCT_PROD_GROUP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTCT_PROD_GROUP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
