*----------------------------------------------------------------------*
* FUNCTION MODULE NAME:ZQTC_SDORDER_GETDETAILEDLIST (Get Subscription Order data)
* PROGRAM DESCRIPTION:Function Module for Sales Order Data
* DEVELOPER: Siva Guda ( SGUDA)
* CREATION DATE:   02/05/2016
* OBJECT ID: E096
* TRANSPORT NUMBER(S): ED2K910734
*----------------------------------------------------------------------*

FUNCTION-POOL ZQTC_SDORDER_GETLIST.         "MESSAGE-ID ..
TYPE-POOLS V45I .

*-- Belegfluss Massenselect -------------------------------------------*
TYPES: BEGIN OF V45I_VBFA.
TYPES:  ORIGIN_VBELN LIKE VBAK-VBELN.
        INCLUDE STRUCTURE VBFAVB.
TYPES: END OF V45I_VBFA.

TYPES: V45I_VBFA_TABL TYPE V45I_VBFA OCCURS 0.
DATA: BEGIN OF TY_THEAD OCCURS 0.
        INCLUDE STRUCTURE THEADVB.
DATA: END OF TY_THEAD.
* INCLUDE LZQTC_SDORDER_GETLISTD...          " Local class definition
DATA: LI_VBAK       TYPE STANDARD TABLE OF VBAK,
      LI_VBAP       TYPE STANDARD TABLE OF VBAPVB,
      LI_VBPA       TYPE STANDARD TABLE OF VBPAVB,
      LI_VEDA       TYPE STANDARD TABLE OF VEDAVB,
      LI_VBKD       TYPE STANDARD TABLE OF VBKDVB,
      LI_THEAD      TYPE STANDARD TABLE OF THEADVB,
      LI_VBFA       TYPE V45I_VBFA_TABL,
      LI_STX_LINES  TYPE STANDARD TABLE OF BAPITEXTLI,
      I_MEMORY_READ LIKE  ORDER_READ-MEM_ACCESS,
      LT_KEYTAB     LIKE ZQTC_SO_RANGE OCCURS 0 WITH HEADER LINE,
      I_THEAD       TYPE THEADVB,
      LI_SALES      TYPE STANDARD TABLE OF SALES_KEY,
      LST_SALES     TYPE SALES_KEY,
      LST_VBAK      TYPE VBAK,
      LV_BAPI_VIEW  TYPE ORDER_VIEW,
      LST_SALES_DOCUMENTS TYPE ZQTC_SO_RANGE.
CONSTANTS: LC_DOWNLOAD_TYPE(3) VALUE '005',
           LC_X(1)    VALUE 'X'.
