FUNCTION-POOL ZQTC_ISM_MATMAS03.            "MESSAGE-ID ..

* INCLUDE LZQTC_ISM_MATMAS03D...             " Local class definition

  TYPES:
    BEGIN OF LTY_S_MARM_DEL,                                            " n_2595170
      DIMID     TYPE T006-DIMID,
      MARM_UEB  TYPE MARM_UEB OCCURS 0,
      MFIELDRES TYPE MFIELDRES OCCURS 0,
    END OF LTY_S_MARM_DEL.
  DATA: I_MARA_UEB LIKE MARA_UEB.
  DATA: I_MAKT_UEB LIKE MAKT_UEB.
  DATA: I_MARC_UEB LIKE MARC_UEB.
  DATA: I_MARD_UEB LIKE MARD_UEB.
  DATA: I_MFHM_UEB LIKE MFHM_UEB.
  DATA: I_MARM_UEB LIKE MARM_UEB.
  DATA: I_MEAN_UEB LIKE MEA1_UEB.
  DATA: I_MBEW_UEB LIKE MBEW_UEB.
  DATA: I_STEU_UEB LIKE STEU_UEB.
  DATA: I_STEUMM_UEB LIKE STEUMM_UEB.
  DATA: I_MLGN_UEB LIKE MLGN_UEB.
  DATA: I_MLGT_UEB LIKE MLGT_UEB.      " //br010797 neu zu 4.0
  DATA: I_MPGD_UEB LIKE MPGD_UEB.
  DATA: I_MPOP_UEB LIKE MPOP_UEB.
  DATA: I_MVEG_UEB LIKE MVEG_UEB.
  DATA: I_MVEU_UEB LIKE MVEU_UEB.
  DATA: I_MVKE_UEB LIKE MVKE_UEB.
  DATA: I_MPRW_UEB LIKE MPRW_UEB.
  DATA: I_LTX1_UEB LIKE LTX1_UEB.
  DATA: I_E1CUCFG_UEB LIKE E1CUCFG_UEB.    "TF 4.7/ALE Material Variants
  DATA: I_E1CUINS_UEB LIKE E1CUINS_UEB.    "TF 4.7/ALE Material Variants
  DATA: I_E1CUVAL_UEB LIKE E1CUVAL_UEB.    "TF 4.7/ALE Material Variants
  DATA: I_E1CUCOM_UEB LIKE E1CUCOM_UEB.    "TF 4.7/ALE Material Variants

  DATA: HELP_MARC_UEB LIKE MARC_UEB.

  DATA: T_MARA_UEB LIKE MARA_UEB OCCURS 0.
  DATA: T_MAKT_UEB LIKE MAKT_UEB OCCURS 0.
  DATA: T_MARC_UEB LIKE MARC_UEB OCCURS 0.
  DATA: T_MARD_UEB LIKE MARD_UEB OCCURS 0.
  DATA: T_MFHM_UEB LIKE MFHM_UEB OCCURS 0.
  DATA: T_MARM_UEB LIKE MARM_UEB OCCURS 0.
  DATA: T_MARM_DEL TYPE SORTED TABLE OF LTY_S_MARM_DEL                  " n_2595170
                        WITH UNIQUE KEY DIMID.                          " n_2595170
  DATA: T_MARM_DIMID TYPE SORTED TABLE OF T006-DIMID                    " n_2595170
                          WITH UNIQUE KEY TABLE_LINE.                   " n_2595170
  DATA: T_MEAN_UEB LIKE MEA1_UEB OCCURS 0.
  DATA: T_MBEW_UEB LIKE MBEW_UEB OCCURS 0.
  DATA: T_STEU_UEB LIKE STEU_UEB OCCURS 0.
  DATA: T_STEUMM_UEB LIKE STEUMM_UEB OCCURS 0.
  DATA: T_MLGN_UEB LIKE MLGN_UEB OCCURS 0.
  DATA: T_MLGT_UEB LIKE MLGT_UEB OCCURS 0.    " //br010797 neu zu 4.0
  DATA: T_MPGD_UEB LIKE MPGD_UEB OCCURS 0.
  DATA: T_MPOP_UEB LIKE MPOP_UEB OCCURS 0.
  DATA: T_MVEG_UEB LIKE MVEG_UEB OCCURS 0.
  DATA: T_MVEU_UEB LIKE MVEU_UEB OCCURS 0.
  DATA: T_MVKE_UEB LIKE MVKE_UEB OCCURS 0.
  DATA: T_MPRW_UEB LIKE MPRW_UEB OCCURS 0.
  DATA: T_LTX1_UEB LIKE LTX1_UEB OCCURS 0.
  DATA: USER_SEGMENTS LIKE EDIDD OCCURS 0 WITH HEADER LINE.  " insert
  DATA: CUST_SEGMENT LIKE EDIDD.
  DATA: I_MFIELDRES LIKE MFIELDRES.
  DATA: I_EDIDD LIKE EDIDD.
                                       " //br neu zu 3.1g
  DATA: T_RES_FIELDS LIKE DELFIELDS OCCURS 0 WITH HEADER LINE.

  DATA: T_MFIELDRES LIKE MFIELDRES OCCURS 0.
  DATA: T_MERRDAT LIKE MERRDAT OCCURS 0.
  DATA: T_EDIDD LIKE EDIDD OCCURS 0.

    DATA: BEGIN OF T_IDOC_MATNR OCCURS 0,
          DOCNUM LIKE EDIDC-DOCNUM,
          MATNR  LIKE MARA-MATNR,
        END   OF T_IDOC_MATNR.
           "
  DATA: BEGIN OF COUNTER,
          TRANC LIKE MARA_UEB-TRANC,
          D_IND LIKE MARA_UEB-D_IND,
        END OF COUNTER.
  DATA T_IDOC_TRANC LIKE MATIDOCTRANC OCCURS 0 WITH HEADER LINE."

  DATA: FLAG_FITS.
  DATA: APPLICATION_SUBRC LIKE SY-SUBRC.
  DATA: SAV_I_MARA_UEB_VPSTA LIKE MARA-VPSTA.
  DATA: lst_matnr   TYPE matnr,
        lst_e1maram TYPE e1maram.
