*&---------------------------------------------------------------------*
*&  Include  ZSCMN_LITHO_TM_R096_SSCRN
*&---------------------------------------------------------------------*



SELECTION-SCREEN BEGIN OF SCREEN 9051 AS SUBSCREEN NO INTERVALS.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 1(23) text-002.
PARAMETERS: p_tmtyp TYPE ztmtype AS LISTBOX VISIBLE LENGTH 20
                    USER-COMMAND tmty.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 1(23) text-003.
PARAMETERS: p_subtyp TYPE zsubtype AS LISTBOX VISIBLE LENGTH 20.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 1(20) text-001.
SELECT-OPTIONS: s_matnr FOR mara-matnr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 1(23) text-004.
PARAMETERS: p_datact TYPE dats.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 1(23) text-005.
PARAMETERS: p_flag TYPE zsubflag AS LISTBOX VISIBLE LENGTH 10.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 1(23) text-006.
PARAMETERS: p_qty TYPE numc13.
SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN END OF SCREEN 9051.
