*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVQTC_JGC_SOC...................................*
FORM GET_DATA_ZVQTC_JGC_SOC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZQTC_JGC_SOCIETY WHERE
(VIM_WHERETAB) .
    CLEAR ZVQTC_JGC_SOC .
ZVQTC_JGC_SOC-MANDT =
ZQTC_JGC_SOCIETY-MANDT .
ZVQTC_JGC_SOC-JRNL_GRP_CODE =
ZQTC_JGC_SOCIETY-JRNL_GRP_CODE .
ZVQTC_JGC_SOC-RELTYP =
ZQTC_JGC_SOCIETY-RELTYP .
ZVQTC_JGC_SOC-SOCIETY =
ZQTC_JGC_SOCIETY-SOCIETY .
ZVQTC_JGC_SOC-SOCIETY_ACRNYM =
ZQTC_JGC_SOCIETY-SOCIETY_ACRNYM .
ZVQTC_JGC_SOC-SOCIETY_NAME =
ZQTC_JGC_SOCIETY-SOCIETY_NAME .
ZVQTC_JGC_SOC-PRICING_RELEVANT =
ZQTC_JGC_SOCIETY-PRICING_RELEVANT .
ZVQTC_JGC_SOC-DIGITAL_RELEVANT =
ZQTC_JGC_SOCIETY-DIGITAL_RELEVANT .
ZVQTC_JGC_SOC-AENAM =
ZQTC_JGC_SOCIETY-AENAM .
ZVQTC_JGC_SOC-AEDAT =
ZQTC_JGC_SOCIETY-AEDAT .
ZVQTC_JGC_SOC-AEZET =
ZQTC_JGC_SOCIETY-AEZET .
    SELECT * FROM TBZ9 WHERE
RELTYP = ZQTC_JGC_SOCIETY-RELTYP .
      SELECT SINGLE * FROM TBZ9A WHERE
RELTYP = TBZ9-RELTYP AND
XRF = TBZ9-XRF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVQTC_JGC_SOC-BEZ50 =
TBZ9A-BEZ50 .
      ENDIF.
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZVQTC_JGC_SOC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVQTC_JGC_SOC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVQTC_JGC_SOC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVQTC_JGC_SOC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_JGC_SOCIETY WHERE
  JRNL_GRP_CODE = ZVQTC_JGC_SOC-JRNL_GRP_CODE AND
  RELTYP = ZVQTC_JGC_SOC-RELTYP AND
  SOCIETY = ZVQTC_JGC_SOC-SOCIETY .
    IF SY-SUBRC = 0.
    DELETE ZQTC_JGC_SOCIETY .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZQTC_JGC_SOCIETY WHERE
  JRNL_GRP_CODE = ZVQTC_JGC_SOC-JRNL_GRP_CODE AND
  RELTYP = ZVQTC_JGC_SOC-RELTYP AND
  SOCIETY = ZVQTC_JGC_SOC-SOCIETY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZQTC_JGC_SOCIETY.
    ENDIF.
ZQTC_JGC_SOCIETY-MANDT =
ZVQTC_JGC_SOC-MANDT .
ZQTC_JGC_SOCIETY-JRNL_GRP_CODE =
ZVQTC_JGC_SOC-JRNL_GRP_CODE .
ZQTC_JGC_SOCIETY-RELTYP =
ZVQTC_JGC_SOC-RELTYP .
ZQTC_JGC_SOCIETY-SOCIETY =
ZVQTC_JGC_SOC-SOCIETY .
ZQTC_JGC_SOCIETY-SOCIETY_ACRNYM =
ZVQTC_JGC_SOC-SOCIETY_ACRNYM .
ZQTC_JGC_SOCIETY-SOCIETY_NAME =
ZVQTC_JGC_SOC-SOCIETY_NAME .
ZQTC_JGC_SOCIETY-PRICING_RELEVANT =
ZVQTC_JGC_SOC-PRICING_RELEVANT .
ZQTC_JGC_SOCIETY-DIGITAL_RELEVANT =
ZVQTC_JGC_SOC-DIGITAL_RELEVANT .
ZQTC_JGC_SOCIETY-AENAM =
ZVQTC_JGC_SOC-AENAM .
ZQTC_JGC_SOCIETY-AEDAT =
ZVQTC_JGC_SOC-AEDAT .
ZQTC_JGC_SOCIETY-AEZET =
ZVQTC_JGC_SOC-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZQTC_JGC_SOCIETY .
    ELSE.
    INSERT ZQTC_JGC_SOCIETY .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVQTC_JGC_SOC-UPD_FLAG,
STATUS_ZVQTC_JGC_SOC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVQTC_JGC_SOC.
  SELECT SINGLE * FROM ZQTC_JGC_SOCIETY WHERE
JRNL_GRP_CODE = ZVQTC_JGC_SOC-JRNL_GRP_CODE AND
RELTYP = ZVQTC_JGC_SOC-RELTYP AND
SOCIETY = ZVQTC_JGC_SOC-SOCIETY .
ZVQTC_JGC_SOC-MANDT =
ZQTC_JGC_SOCIETY-MANDT .
ZVQTC_JGC_SOC-JRNL_GRP_CODE =
ZQTC_JGC_SOCIETY-JRNL_GRP_CODE .
ZVQTC_JGC_SOC-RELTYP =
ZQTC_JGC_SOCIETY-RELTYP .
ZVQTC_JGC_SOC-SOCIETY =
ZQTC_JGC_SOCIETY-SOCIETY .
ZVQTC_JGC_SOC-SOCIETY_ACRNYM =
ZQTC_JGC_SOCIETY-SOCIETY_ACRNYM .
ZVQTC_JGC_SOC-SOCIETY_NAME =
ZQTC_JGC_SOCIETY-SOCIETY_NAME .
ZVQTC_JGC_SOC-PRICING_RELEVANT =
ZQTC_JGC_SOCIETY-PRICING_RELEVANT .
ZVQTC_JGC_SOC-DIGITAL_RELEVANT =
ZQTC_JGC_SOCIETY-DIGITAL_RELEVANT .
ZVQTC_JGC_SOC-AENAM =
ZQTC_JGC_SOCIETY-AENAM .
ZVQTC_JGC_SOC-AEDAT =
ZQTC_JGC_SOCIETY-AEDAT .
ZVQTC_JGC_SOC-AEZET =
ZQTC_JGC_SOCIETY-AEZET .
    SELECT * FROM TBZ9 WHERE
RELTYP = ZQTC_JGC_SOCIETY-RELTYP .
      SELECT SINGLE * FROM TBZ9A WHERE
RELTYP = TBZ9-RELTYP AND
XRF = TBZ9-XRF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVQTC_JGC_SOC-BEZ50 =
TBZ9A-BEZ50 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVQTC_JGC_SOC-BEZ50 .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZVQTC_JGC_SOC-BEZ50 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVQTC_JGC_SOC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVQTC_JGC_SOC-JRNL_GRP_CODE TO
ZQTC_JGC_SOCIETY-JRNL_GRP_CODE .
MOVE ZVQTC_JGC_SOC-RELTYP TO
ZQTC_JGC_SOCIETY-RELTYP .
MOVE ZVQTC_JGC_SOC-SOCIETY TO
ZQTC_JGC_SOCIETY-SOCIETY .
MOVE ZVQTC_JGC_SOC-MANDT TO
ZQTC_JGC_SOCIETY-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZQTC_JGC_SOCIETY'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZQTC_JGC_SOCIETY TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZQTC_JGC_SOCIETY'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVQTC_JGC_SOC USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZQTC_JGC_SOCIETY-MANDT =
ZVQTC_JGC_SOC-MANDT .
ZQTC_JGC_SOCIETY-JRNL_GRP_CODE =
ZVQTC_JGC_SOC-JRNL_GRP_CODE .
ZQTC_JGC_SOCIETY-RELTYP =
ZVQTC_JGC_SOC-RELTYP .
ZQTC_JGC_SOCIETY-SOCIETY =
ZVQTC_JGC_SOC-SOCIETY .
ZQTC_JGC_SOCIETY-SOCIETY_ACRNYM =
ZVQTC_JGC_SOC-SOCIETY_ACRNYM .
ZQTC_JGC_SOCIETY-SOCIETY_NAME =
ZVQTC_JGC_SOC-SOCIETY_NAME .
ZQTC_JGC_SOCIETY-PRICING_RELEVANT =
ZVQTC_JGC_SOC-PRICING_RELEVANT .
ZQTC_JGC_SOCIETY-DIGITAL_RELEVANT =
ZVQTC_JGC_SOC-DIGITAL_RELEVANT .
ZQTC_JGC_SOCIETY-AENAM =
ZVQTC_JGC_SOC-AENAM .
ZQTC_JGC_SOCIETY-AEDAT =
ZVQTC_JGC_SOC-AEDAT .
ZQTC_JGC_SOCIETY-AEZET =
ZVQTC_JGC_SOC-AEZET .
    SELECT * FROM TBZ9 WHERE
RELTYP = ZQTC_JGC_SOCIETY-RELTYP .
      SELECT SINGLE * FROM TBZ9A WHERE
RELTYP = TBZ9-RELTYP AND
XRF = TBZ9-XRF AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVQTC_JGC_SOC-BEZ50 =
TBZ9A-BEZ50 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVQTC_JGC_SOC-BEZ50 .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZVQTC_JGC_SOC-BEZ50 .
    ENDIF.
ENDFORM.
